"""
CSV and JSON Data Persistence for ML-MCDM.

This module provides the `CsvWriter` class, which handles the serialization 
of all structured numerical output generated by the pipeline. It manages 
file categorization into phase-specific subdirectories and ensures 
consistent formatting across weights, rankings, scores, and forecasts.

Directory Structure
-------------------
Files are organized under ``output/result/csv/<phase>/``:
- **weighting/**: CRITIC weights, yearly analysis, and global summaries.
- **mcdm/**: Method-specific scores (TOPSIS, VIKOR, etc.) per criterion.
- **ranking/**: Final composite rankings and percentile distributions.
- **forecasting/**: Predictions, intervals, importance, and CV diagnostics.
- **sensitivity/**: Rank disruption metrics and robustness summaries.

Key Features
------------
- **Atomic Writes**: Ensures directory existence before file creation.
- **Phase-Aware Partitioning**: Segregates data to simplify auditability.
- **Z-Score & Percentile Calculation**: Automatically appends statistical 
  context to ranking outputs.
- **Manifest Integrity**: Generates SHA-256 hashes for all saved artifacts 
  to guarantee data lineage.
"""

from __future__ import annotations

import json
import numpy as np
import pandas as pd
from pathlib import Path
from typing import Any, Dict, List, Optional
import logging

_logger = logging.getLogger(__name__)


class CsvWriter:
    """
    Writer for structured pipeline artifacts.

    Attributes
    ----------
    csv_dir : Path
        Base directory for all CSV outputs.
    weighting_dir : Path
        Directory for weighting results.
    mcdm_dir : Path
        Directory for MCDM method scores.
    ranking_dir : Path
        Directory for final rankings.
    forecasting_dir : Path
        Directory for ML forecasting results.
    sensitivity_dir : Path
        Directory for sensitivity analysis data.
    """

    # Canonical phase names
    PHASES = ('weighting', 'mcdm', 'ranking', 'forecasting', 'sensitivity')

    def __init__(self, base_output_dir: str = 'output/result'):
        """
        Initialize the CSV writer.

        Parameters
        ----------
        base_output_dir : str, default='output/result'
            The root directory for output. A 'csv/' subdirectory will 
            be created within it.
        """
        from . import _sanitize_output_dir
        base = _sanitize_output_dir(base_output_dir)
        self.csv_dir = base / 'csv'
        # Create one subdirectory per phase
        for phase in self.PHASES:
            (self.csv_dir / phase).mkdir(parents=True, exist_ok=True)
            setattr(self, f'{phase}_dir', self.csv_dir / phase)
        # Backward-compat alias
        self.results_dir = self.csv_dir
        self._saved_files: List[str] = []

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _record(self, path: Path) -> str:
        s = str(path)
        self._saved_files.append(s)
        return s

    def _save_csv(self, df: pd.DataFrame, name: str,
                  directory: Optional[Path] = None,
                  float_fmt: str = '%.6g', **kwargs) -> str:
        d = directory if directory is not None else self.csv_dir
        path = d / name
        df.to_csv(path, float_format=float_fmt, **kwargs)
        return self._record(path)

    def _save_json(self, obj: Any, name: str,
                   directory: Optional[Path] = None) -> str:
        d = directory if directory is not None else self.csv_dir
        path = d / name
        with open(path, 'w', encoding='utf-8') as f:
            json.dump(obj, f, indent=2, default=str, ensure_ascii=False)
        return self._record(path)

    def get_saved_files(self) -> List[str]:
        return list(self._saved_files)

    # ==================================================================
    #  1. WEIGHTS
    # ==================================================================

    def save_weights(self, weights: Dict[str, Any],
                     subcriteria: List[str]) -> str:
        """
        Save CRITIC weighting results to weights_analysis.csv.

        Parameters
        ----------
        weights : Dict[str, Any]
            The weights dictionary containing 'global_sc_weights', 
            'criterion_weights', and 'details' with Monte Carlo 
            diagnostics.
        subcriteria : List[str]
            Ordered list of subcriteria names for indexing.

        Returns
        -------
        str
            The absolute path to the saved CSV file.
        """
        global_sc_w  = weights.get('global_sc_weights', {})
        criterion_w  = weights.get('criterion_weights', {})
        sc_arr       = np.asarray(weights.get('sc_array', [global_sc_w.get(sc, 0.0) for sc in subcriteria]))
        details      = weights.get('details', {})
        l1           = details.get('level1', {})

        # Build per-SC lookup for Level 1 diagnostics
        sc_to_crit: Dict[str, str] = {}
        for crit_id, sc_list in {
            cid: data.get('local_sc_weights', {}).keys()
            for cid, data in l1.items()
        }.items():
            for sc in sc_list:
                sc_to_crit[sc] = crit_id

        rows = []
        for i, sc in enumerate(subcriteria):
            crit_id = sc_to_crit.get(sc, '')
            l1_entry = l1.get(crit_id, {})
            local_w  = l1_entry.get('local_sc_weights', {})
            mc       = l1_entry.get('mc_diagnostics', {})
            row = {
                'Subcriteria':    sc,
                'Criterion':      crit_id,
                'Global_Weight':  float(global_sc_w.get(sc, sc_arr[i] if i < len(sc_arr) else 0.0)),
                'Criterion_Weight': float(criterion_w.get(crit_id, 0.0)),
                'Local_SC_Weight': float(local_w.get(sc, 0.0)),
                'MC_Mean':        float(mc.get('mean_weights', {}).get(sc, 0.0)),
                'MC_Std':         float(mc.get('std_weights', {}).get(sc, 0.0)),
                'MC_CV':          float(mc.get('cv_weights', {}).get(sc, 0.0)),
                'CI_Lower_2_5':   float(mc.get('ci_lower_2_5', {}).get(sc, 0.0)),
                'CI_Upper_97_5':  float(mc.get('ci_upper_97_5', {}).get(sc, 0.0)),
            }
            rows.append(row)

        df = pd.DataFrame(rows).set_index('Subcriteria')
        df['Rank_Global'] = df['Global_Weight'].rank(ascending=False, method='min').astype(int)

        # Append criterion-level summary rows at the bottom
        crit_rows = []
        for crit_id, v in sorted(criterion_w.items()):
            l2_diag = details.get('level2', {}).get('mc_diagnostics', {})
            crit_rows.append({
                'Subcriteria': f'[CRITERION] {crit_id}',
                'Criterion': crit_id,
                'Global_Weight': float(v),
                'Criterion_Weight': float(v),
                'Local_SC_Weight': float(v),
                'MC_Mean': float(l2_diag.get('mean_weights', {}).get(crit_id, v)),
                'MC_Std':  float(l2_diag.get('std_weights', {}).get(crit_id, 0.0)),
                'MC_CV':   float(l2_diag.get('cv_weights', {}).get(crit_id, 0.0)),
                'CI_Lower_2_5':  float(l2_diag.get('ci_lower_2_5', {}).get(crit_id, 0.0)),
                'CI_Upper_97_5': float(l2_diag.get('ci_upper_97_5', {}).get(crit_id, 0.0)),
                'Rank_Global': 0,
            })

        if crit_rows:
            crit_df = pd.DataFrame(crit_rows).set_index('Subcriteria')
            df = pd.concat([df, crit_df])

        return self._save_csv(df, 'weights_analysis.csv',
                                directory=self.weighting_dir)

    # ==================================================================
    #  2. RANKINGS
    # ==================================================================

    def save_rankings(self, ranking_result: Any,
                      provinces: List[str]) -> str:
        """
        Save final composite rankings to final_rankings.csv.

        Calculates percentiles, Z-scores, and tier assignments based on 
        the composite ER scores.

        Parameters
        ----------
        ranking_result : RankingResult
            The results containing final_scores and final_ranking.
        provinces : List[str]
            Fallback list of province names if result index is missing.

        Returns
        -------
        str
            The absolute path to the saved CSV file.
        """
        scores = ranking_result.final_scores
        ranks = ranking_result.final_ranking

        # Use the active province list from the result's index so that
        active_provinces = (
            list(scores.index)
            if hasattr(scores, 'index')
            else provinces
        )

        df = pd.DataFrame({
            'Province': active_provinces,
            'Composite_Score': np.asarray(scores.values if hasattr(scores, 'values') else scores),
            'Composite_Rank': np.asarray(ranks.values if hasattr(ranks, 'values') else ranks, dtype=int),
        })

        n = len(df)
        df['Percentile'] = ((n - df['Composite_Rank'] + 1) / n * 100).round(1)

        mean_s = df['Composite_Score'].mean()
        std_s = df['Composite_Score'].std()
        df['Z_Score'] = ((df['Composite_Score'] - mean_s) / std_s).round(4) if std_s > 0 else 0

        df['Tier'] = pd.cut(
            df['Composite_Rank'],
            bins=[0, n * 0.1, n * 0.25, n * 0.5, n * 0.75, n + 1],
            labels=['Elite (Top 10%)', 'High (10-25%)', 'Upper-Mid (25-50%)',
                    'Lower-Mid (50-75%)', 'Low (75-100%)'],
        )

        df['Kendall_W'] = ranking_result.kendall_w

        df = df.sort_values('Composite_Rank').reset_index(drop=True)
        df.index = df.index + 1
        df.index.name = 'Position'
        return self._save_csv(df, 'final_rankings.csv', float_fmt='%.4f',
                                directory=self.mcdm_dir)

    # ==================================================================
    #  3. MCDM SCORES PER CRITERION  (long format, all years)
    # ==================================================================

    def save_mcdm_scores_by_criterion(
        self, multi_year_results: Dict[int, Any],
    ) -> Dict[str, str]:
        """
        Write per-criterion MCDM score files spanning all years.

        Each file is long-format: one row per (Year, Province) pair with 
        columns for TOPSIS, VIKOR, PROMETHEE, COPRAS, EDAS, and Base.

        Parameters
        ----------
        multi_year_results : Dict[int, Any]
            Dictionary mapping year to ranking results for that year.

        Returns
        -------
        Dict[str, str]
            Dictionary mapping criterion ID to the absolute path of its 
            saved CSV file.
        """
        saved: Dict[str, str] = {}
        if not multi_year_results:
            return saved

        _METHODS = ['TOPSIS', 'VIKOR', 'PROMETHEE', 'COPRAS', 'EDAS', 'Base']
        years = sorted(multi_year_results.keys())
        crit_rows: Dict[str, List[Dict]] = {}

        for yr in years:
            yr_res = multi_year_results[yr]
            method_scores = getattr(yr_res, 'criterion_method_scores', {})
            er_res = getattr(yr_res, 'er_result', None)
            crit_beliefs = getattr(er_res, 'criterion_beliefs', {}) if er_res else {}

            for crit_id, crit_data in sorted(method_scores.items()):
                if crit_id not in crit_rows:
                    crit_rows[crit_id] = []
                first_series = next(iter(crit_data.values()), None)
                if first_series is None:
                    continue
                prov_list = (
                    list(first_series.index)
                    if hasattr(first_series, 'index')
                    else []
                )
                for prov in prov_list:
                    row: Dict[str, Any] = {'Year': yr, 'Province': prov}
                    for method in _METHODS:
                        series = crit_data.get(method)
                        if series is not None and hasattr(series, 'loc') and prov in series.index:
                            row[method] = float(series.loc[prov])
                        else:
                            row[method] = float('nan')
                    crit_rows[crit_id].append(row)

        for crit_id, rows in crit_rows.items():
            if not rows:
                continue
            df = pd.DataFrame(rows)
            df = df.sort_values(['Year', 'Province']).reset_index(drop=True)
            df.index.name = 'RowID'
            fname = f'mcdm_scores_{crit_id}.csv'
            saved[crit_id] = self._save_csv(
                df, fname, directory=self.mcdm_dir, float_fmt='%.4f')

        return saved

    # ==================================================================
    #  3b. MCDM COMPOSITE SCORES  (long format, all years)
    # ==================================================================

    def save_mcdm_composite_scores_all_years(
        self, multi_year_results: Dict[int, Any],
    ) -> Optional[str]:
        """
        Write composite MCDM scores for all years.

        Produces a single long-format file containing the average score 
        per method across all criteria, plus the final ER composite score.

        Parameters
        ----------
        multi_year_results : Dict[int, Any]
            Dictionary mapping year to ranking results for that year.

        Returns
        -------
        str, optional
            The absolute path to the saved CSV file, or None if no 
            results were provided.
        """
        if not multi_year_results:
            return None

        _METHODS = ['TOPSIS', 'VIKOR', 'PROMETHEE', 'COPRAS', 'EDAS', 'Base']
        years = sorted(multi_year_results.keys())
        rows: List[Dict] = []

        for yr in years:
            yr_res = multi_year_results[yr]
            method_scores = getattr(yr_res, 'criterion_method_scores', {})
            final_scores  = getattr(yr_res, 'final_scores', None)

            # Determine active province list
            if final_scores is not None and hasattr(final_scores, 'index'):
                active_provinces = list(final_scores.index)
            else:
                first_crit = next(iter(method_scores.values()), {})
                first_series = next(iter(first_crit.values()), None)
                active_provinces = (
                    list(first_series.index)
                    if first_series is not None and hasattr(first_series, 'index')
                    else []
                )

            if not active_provinces or not method_scores:
                continue

            # Sum scores across criteria per method per province
            method_sums: Dict[str, Dict[str, float]] = {m: {} for m in _METHODS}
            method_counts: Dict[str, Dict[str, int]] = {m: {} for m in _METHODS}
            for m in _METHODS:
                for p in active_provinces:
                    method_sums[m][p] = 0.0
                    method_counts[m][p] = 0

            for _crit_id, crit_data in method_scores.items():
                for method in _METHODS:
                    series = crit_data.get(method)
                    if series is None:
                        continue
                    for prov in active_provinces:
                        if hasattr(series, 'loc') and prov in series.index:
                            val = float(series.loc[prov])
                            if not np.isnan(val):
                                method_sums[method][prov] += val
                                method_counts[method][prov] += 1

            for prov in active_provinces:
                row: Dict[str, Any] = {'Year': yr, 'Province': prov}
                for method in _METHODS:
                    cnt = method_counts[method][prov]
                    row[method] = (
                        method_sums[method][prov] / cnt if cnt > 0 else float('nan')
                    )
                # ER = final composite ER score
                if final_scores is not None and hasattr(final_scores, 'loc') and prov in final_scores.index:
                    row['ER'] = float(final_scores.loc[prov])
                else:
                    row['ER'] = float('nan')
                rows.append(row)

        if not rows:
            return None
        df = pd.DataFrame(rows)
        df = df.sort_values(['Year', 'Province']).reset_index(drop=True)
        df.index.name = 'RowID'
        return self._save_csv(
            df, 'mcdm_scores_composite.csv',
            directory=self.mcdm_dir, float_fmt='%.4f')

    # ==================================================================
    #  4. RANK COMPARISON (all methods x all criteria)
    # ==================================================================

    def save_rank_comparison(self, ranking_result: Any,
                             provinces: List[str]) -> str:
        # The final ranking's province list is the authoritative active set.
        active_provinces = (
            list(ranking_result.final_ranking.index)
            if hasattr(ranking_result.final_ranking, 'index')
            else provinces
        )

        all_ranks = {}
        for crit_id, method_ranks in ranking_result.criterion_method_ranks.items():
            for method, ranks_series in method_ranks.items():
                col = f'{crit_id}_{method}'
                if hasattr(ranks_series, 'reindex'):
                    # Reindex to the global active province list so that
                    # provinces absent from this criterion's active subset
                    # are represented as NaN rather than sizing mismatches.
                    vals = ranks_series.reindex(active_provinces).values
                else:
                    vals = np.asarray(ranks_series)
                all_ranks[col] = vals

        df = pd.DataFrame(all_ranks, index=active_provinces)
        df.index.name = 'Province'

        df['Mean_Rank'] = df.mean(axis=1).round(2)
        df['Median_Rank'] = df.median(axis=1).round(2)
        df['StdDev_Rank'] = df.std(axis=1).round(2)
        summary = ['Mean_Rank', 'Median_Rank', 'StdDev_Rank']
        base = df.drop(columns=summary, errors='ignore')
        df['Best_Rank'] = base.min(axis=1)
        df['Worst_Rank'] = base.max(axis=1)
        df['Rank_Range'] = df['Worst_Rank'] - df['Best_Rank']

        return self._save_csv(df, 'mcdm_rank_comparison.csv', float_fmt='%.0f',
                                directory=self.mcdm_dir)

    # ==================================================================
    #  5. FORECAST RESULTS
    # ==================================================================

    def save_forecast_results(self, forecast_result: Any) -> Dict[str, str]:
        """
        Save all machine learning forecasting outcomes.

        Persists predictions, intervals, model contributions, performance 
        metrics, and feature importance. Also generates an integrity 
        manifest with SHA-256 hashes.

        Parameters
        ----------
        forecast_result : UnifiedForecastResult
            The comprehensive forecasting result object.

        Returns
        -------
        Dict[str, str]
            Dictionary mapping artifact keys to their absolute file paths.
        """
        saved = {}
        _dir = self.forecasting_dir

        # Predictions
        try:
            preds = forecast_result.predictions
            if preds is not None and not preds.empty:
                saved['predictions'] = self._save_csv(
                    preds, 'forecast_predictions.csv', directory=_dir, float_fmt='%.4f')
        except Exception as _exc:
            _logger.debug('section skipped: %s', _exc)

        # Prediction intervals
        try:
            intervals = forecast_result.prediction_intervals
            if intervals:
                lower = intervals.get('lower')
                upper = intervals.get('upper')
                if lower is not None and upper is not None:
                    cols_dict = {}
                    for col in lower.columns:
                        cols_dict[f'{col}_lower'] = lower[col]
                        cols_dict[f'{col}_upper'] = upper[col]
                        if col in forecast_result.predictions.columns:
                            cols_dict[f'{col}_point'] = forecast_result.predictions[col]
                            cols_dict[f'{col}_width'] = upper[col] - lower[col]
                    combined = pd.concat(cols_dict, axis=1)
                    combined.index.name = 'Entity'
                    saved['prediction_intervals'] = self._save_csv(
                        combined, 'prediction_intervals.csv',
                        directory=_dir, float_fmt='%.4f')
        except Exception as _exc:
            _logger.debug('section skipped: %s', _exc)

        # Model contributions
        try:
            contrib = forecast_result.model_contributions
            if contrib:
                df = pd.DataFrame([
                    {'Model': k, 'Weight': v, 'Rank': 0, 'Weight_Pct': f'{v*100:.1f}%'}
                    for k, v in sorted(contrib.items(), key=lambda x: x[1], reverse=True)
                ])
                df['Rank'] = range(1, len(df) + 1)
                df = df.set_index('Rank')
                saved['model_contributions'] = self._save_csv(
                    df, 'model_contributions.csv', directory=_dir, float_fmt='%.6f')
        except Exception as _exc:
            _logger.debug('section skipped: %s', _exc)

        # Model performance
        try:
            perf = forecast_result.model_performance
            if perf:
                # Separate scalar metrics from list-valued per-criterion RMSE fields
                _scalar_rows: list = []
                _crit_rmse_rows: list = []
                for m, metrics in perf.items():
                    scalar = {
                        k: v for k, v in metrics.items()
                        if not isinstance(v, (list, np.ndarray))
                    }
                    _scalar_rows.append({'Model': m, **scalar})
                    means = metrics.get('per_criterion_rmse_mean', [])
                    stds  = metrics.get('per_criterion_rmse_std', [])
                    if means:
                        row: dict = {'Model': m}
                        for i, (mu, sd) in enumerate(zip(means, stds)):
                            row[f'C{i + 1:02d}_rmse_mean'] = float(mu)
                            row[f'C{i + 1:02d}_rmse_std']  = float(sd)
                        _crit_rmse_rows.append(row)
                df = pd.DataFrame(_scalar_rows).set_index('Model')
                saved['model_performance'] = self._save_csv(
                    df, 'model_performance.csv', directory=_dir, float_fmt='%.4f')
                if _crit_rmse_rows:
                    df_crit = pd.DataFrame(_crit_rmse_rows).set_index('Model')
                    saved['per_criterion_cv_rmse'] = self._save_csv(
                        df_crit, 'per_criterion_cv_rmse.csv',
                        directory=_dir, float_fmt='%.6f')
        except Exception as _exc:
            _logger.debug('section skipped: %s', _exc)

        # Feature importance
        try:
            imp = forecast_result.feature_importance
            if imp is not None and not imp.empty:
                imp_copy = imp.copy()
                if 'Importance' not in imp_copy.columns and len(imp_copy.columns) > 0:
                    imp_copy['Importance'] = imp_copy.iloc[:, 0]
                imp_copy = imp_copy.sort_values('Importance', ascending=False)
                imp_copy['Cumulative'] = imp_copy['Importance'].cumsum()
                imp_copy['Rank'] = range(1, len(imp_copy) + 1)
                saved['feature_importance'] = self._save_csv(
                    imp_copy, 'feature_importance.csv', directory=_dir, float_fmt='%.6f')
        except Exception as _exc:
            _logger.debug('section skipped: %s', _exc)

        # Cross-validation scores
        try:
            cv = forecast_result.cross_validation_scores
            if cv:
                rows = {}
                for model, scores in cv.items():
                    row = {f'Fold_{i+1}': s for i, s in enumerate(scores)}
                    row.update(Mean=np.nanmean(scores), StdDev=np.nanstd(scores),
                               Min=np.nanmin(scores), Max=np.nanmax(scores))
                    rows[model] = row
                df = pd.DataFrame(rows).T
                df.index.name = 'Model'
                saved['cross_validation'] = self._save_csv(
                    df, 'cross_validation_scores.csv', directory=_dir, float_fmt='%.4f')
        except Exception as _exc:
            _logger.debug('section skipped: %s', _exc)

        # Holdout performance
        try:
            holdout = forecast_result.holdout_performance
            if holdout:
                df = pd.DataFrame([holdout])
                df.index = ['Holdout']
                df.index.name = 'Set'
                saved['holdout'] = self._save_csv(
                    df, 'holdout_performance.csv', directory=_dir, float_fmt='%.4f')
        except Exception as _exc:
            _logger.debug('section skipped: %s', _exc)

        # Forecast CRITIC criterion weights (derived from the predicted cross-section)
        try:
            fcw = getattr(forecast_result, 'forecast_criterion_weights', None)
            if fcw:
                df = pd.DataFrame([
                    {'Criterion': crit, 'CRITIC_Weight': w,
                     'CRITIC_Weight_Pct': f'{w * 100:.2f}%'}
                    for crit, w in sorted(fcw.items())
                ]).set_index('Criterion')
                df['Rank'] = df['CRITIC_Weight'].rank(ascending=False, method='min').astype(int)
                saved['forecast_criterion_weights'] = self._save_csv(
                    df, 'forecast_criterion_weights.csv',
                    directory=_dir, float_fmt='%.6f')
        except Exception as _exc:
            _logger.debug('section skipped: %s', _exc)

        # Forecast ranking (provinces ranked by CRITIC-weighted composite score)
        try:
            composite = getattr(forecast_result, 'composite_predictions', None)
            if composite is not None and len(composite) > 0:
                rank_df = composite.rename('Composite_Score').to_frame()
                rank_df.index.name = 'Province'
                rank_df['Rank'] = rank_df['Composite_Score'].rank(
                    ascending=False, method='min').astype(int)
                rank_df = rank_df.sort_values('Rank').reset_index()
                rank_df.index = rank_df.index + 1
                rank_df.index.name = 'Position'
                n = len(rank_df)
                rank_df['Percentile'] = ((n - rank_df['Rank'] + 1) / n * 100).round(1)
                saved['forecast_ranking'] = self._save_csv(
                    rank_df, 'forecast_ranking.csv',
                    directory=_dir, float_fmt='%.4f')
        except Exception as _exc:
            _logger.debug('section skipped: %s', _exc)

        # Forecast summary JSON
        try:
            summary = {
                'n_models': len(forecast_result.model_contributions) if forecast_result.model_contributions else 0,
                'n_predictions': len(forecast_result.predictions) if forecast_result.predictions is not None else 0,
                'model_weights': forecast_result.model_contributions,
                'holdout_performance': forecast_result.holdout_performance,
                'training_info': {
                    k: v for k, v in (forecast_result.training_info or {}).items()
                    if k not in ('y_test', 'y_pred', 'test_entities', 'X_test')
                },
                'data_summary': forecast_result.data_summary,
            }
            saved['summary'] = self._save_json(summary, 'forecast_summary.json',
                                               directory=_dir)
        except Exception as _exc:
            _logger.debug('section skipped: %s', _exc)

        # -------------------------------------------------------------
        # PHASE 5 EXTENSIONS
        # -------------------------------------------------------------
        try:
            if hasattr(forecast_result, 'individual_model_predictions') and forecast_result.individual_model_predictions:
                # model preds are dict of model_name -> (n_samples, n_criteria)
                import numpy as _np
                records = []
                for mod, preds in forecast_result.individual_model_predictions.items():
                    # Flatten into a format suitable for CSV
                    df = pd.DataFrame(_np.asarray(preds))
                    df.columns = [f'C{i:02d}' for i in range(df.shape[1])]
                    df['Model'] = mod
                    records.append(df)
                if records:
                    comb = pd.concat(records, ignore_index=True)
                    saved['individual_model_predictions'] = self._save_csv(
                        comb, 'individual_model_predictions.csv', directory=_dir, float_fmt='%.6f')
        except Exception as _e:
            _logger.debug(f"Failed to write individual_model_predictions: {_e}")

        try:
            if hasattr(forecast_result, 'forecast_residuals') and forecast_result.forecast_residuals is not None:
                saved['forecast_residuals'] = self._save_csv(
                    pd.DataFrame(forecast_result.forecast_residuals), 'forecast_residuals.csv', directory=_dir, float_fmt='%.6f')
        except Exception as _e:
            _logger.debug(f"Failed to write forecast_residuals: {_e}")

        try:
            if hasattr(forecast_result, 'calibration_summary') and forecast_result.calibration_summary:
                df = pd.DataFrame([
                    {'Criterion': k, 'n_cal': v.get('n_cal', 0), 'q_hat': v.get('q_hat', 0.0)}
                    for k, v in forecast_result.calibration_summary.items()
                ])
                saved['calibration_summary'] = self._save_csv(
                    df, 'calibration_summary.csv', directory=_dir, float_fmt='%.6f')
        except Exception as _e:
            _logger.debug(f"Failed to write calibration_summary: {_e}")

        try:
            if hasattr(forecast_result, 'interval_coverage_by_criterion') and forecast_result.interval_coverage_by_criterion:
                df = pd.DataFrame([
                    {'Criterion': k, 'Coverage': v}
                    for k, v in forecast_result.interval_coverage_by_criterion.items()
                ])
                saved['interval_coverage_by_criterion'] = self._save_csv(
                    df, 'interval_coverage_by_criterion.csv', directory=_dir, float_fmt='%.6f')
        except Exception as _e:
            _logger.debug(f"Failed to write interval_coverage_by_criterion: {_e}")

        try:
            if hasattr(forecast_result, 'interval_width_summary') and forecast_result.interval_width_summary is not None:
                saved['interval_width_summary'] = self._save_csv(
                    forecast_result.interval_width_summary, 'interval_width_summary.csv', directory=_dir, float_fmt='%.6f')
        except Exception as _e:
            _logger.debug(f"Failed to write interval_width_summary: {_e}")

        try:
            if hasattr(forecast_result, 'entity_error_summary') and forecast_result.entity_error_summary is not None:
                saved['entity_error_summary'] = self._save_csv(
                    forecast_result.entity_error_summary, 'entity_error_summary.csv', directory=_dir, float_fmt='%.6f')
        except Exception as _e:
            _logger.debug(f"Failed to write entity_error_summary: {_e}")

        try:
            if hasattr(forecast_result, 'worst_predictions') and forecast_result.worst_predictions is not None:
                saved['worst_predictions'] = self._save_csv(
                    forecast_result.worst_predictions, 'worst_predictions.csv', directory=_dir, float_fmt='%.6f')
        except Exception as _e:
            _logger.debug(f"Failed to write worst_predictions: {_e}")

        try:
            if hasattr(forecast_result, 'forecast_metadata') and forecast_result.forecast_metadata:
                df = pd.DataFrame([forecast_result.forecast_metadata])
                saved['forecast_metadata'] = self._save_csv(
                    df, 'forecast_metadata.csv', directory=_dir)
        except Exception as _e:
            _logger.debug(f"Failed to write forecast_metadata: {_e}")

        # -------------------------------------------------------------
        # MANIFEST VALIDATION (Phase 5)
        # -------------------------------------------------------------
        manifest_records = []
        import hashlib
        for key, filepath in saved.items():
            path_obj = Path(filepath)
            if not path_obj.exists():
                raise FileNotFoundError(f"IntegrityError: Expected artifact missing at {filepath}")
            
            sha256 = hashlib.sha256()
            with open(path_obj, 'rb') as f:
                for chunk in iter(lambda: f.read(4096), b""):
                    sha256.update(chunk)
            
            rows, cols = 0, 0
            if path_obj.suffix.lower() == '.csv':
                try:
                    df = pd.read_csv(path_obj)
                    rows, cols = df.shape
                except Exception:
                    pass
                    
            manifest_records.append({
                'artifact_key': key,
                'file_name': path_obj.name,
                'sha256': sha256.hexdigest(),
                'rows': rows,
                'cols': cols,
                'size_bytes': path_obj.stat().st_size
            })
            
        if manifest_records:
            manifest_df = pd.DataFrame(manifest_records)
            manifest_path = self._save_csv(manifest_df, 'artifact_manifest.csv', directory=_dir)
            saved['artifact_manifest'] = manifest_path

        return saved

    def save_model_comparison(self, model_comparison: List[Any]) -> str:
        """
        Write per-model holdout evaluation metrics.

        Parameters
        ----------
        model_comparison : List[ModelHoldoutResult]
            List of results containing metrics (R2, RMSE, MAE) and 
            best-model indicators.

        Returns
        -------
        str
            The absolute path to the saved CSV file, or an empty string 
             if no comparison data was provided.
        """
        if not model_comparison:
            return ''

        # Identify key models for the narrative Note column
        best     = next((r for r in model_comparison if r.is_best), None)
        ens_r    = next((r for r in model_comparison if r.model_name == 'Ensemble'), None)
        base_r   = next(
            (r for r in model_comparison
             if r.model_name != 'Ensemble' and not np.isnan(r.holdout_r2)),
            None,
        )

        def _note(r: Any) -> str:
            if not r.is_best:
                return ''
            if best and ens_r and base_r:
                if r.model_name == 'Ensemble':
                    return (
                        f"Best model: Ensemble (R²={r.holdout_r2:.4f}) "
                        f"outperforms best base model "
                        f"{base_r.model_name} (R²={base_r.holdout_r2:.4f})"
                    )
                else:
                    ens_r2 = ens_r.holdout_r2 if ens_r else float('nan')
                    return (
                        f"Best model: {r.model_name} (R²={r.holdout_r2:.4f}) "
                        f"outperforms Ensemble (R²={ens_r2:.4f})"
                    )
            return 'Best model on holdout set'

        rows = []
        for r in model_comparison:
            rows.append({
                'Model':        r.model_name,
                'Holdout_R2':   r.holdout_r2,
                'Holdout_RMSE': r.holdout_rmse,
                'Holdout_MAE':  r.holdout_mae,
                'Is_Best':      r.is_best,
                'Note':         _note(r),
            })

        df = pd.DataFrame(rows).set_index('Model')
        return self._save_csv(
            df, 'model_comparison_performance.csv',
            directory=self.forecasting_dir, float_fmt='%.6f',
        )

    # ==================================================================
    #  6. SENSITIVITY / ANALYSIS
    # ==================================================================

    def save_analysis_results(self, analysis_results: Dict[str, Any]) -> Dict[str, str]:
        """
        Save sensitivity and validation analysis outcomes.

        Persists feature importance stability, model impact, and ER-specific 
        uncertainties.

        Parameters
        ----------
        analysis_results : Dict[str, Any]
            Dictionary containing 'sensitivity' results.

        Returns
        -------
        Dict[str, str]
            Dictionary mapping artifact keys to their absolute file paths.
        """
        saved = {}
        sens = analysis_results.get('sensitivity')
        if sens is None:
            return saved
        
        _dir = self.mcdm_dir / 'sensitivity'
        _dir.mkdir(parents=True, exist_ok=True)

        # ML Sensitivity
        try:
            ml = getattr(sens, 'ml_sensitivity', None)
            if ml is not None and ml.feature_importance_cv:
                df = pd.DataFrame([
                    {
                        'Feature': k,
                        'Importance_Mean': ml.feature_importance_mean.get(k, 0),
                        'Importance_CV': v,
                        'Rank_Stability': ml.feature_importance_rank_stability.get(k, 0),
                    }
                    for k, v in sorted(
                        ml.feature_importance_cv.items(),
                        key=lambda x: x[1], reverse=True
                    )
                ]).set_index('Feature')
                saved['ml_feature_importance'] = self._save_csv(
                    df, 'sensitivity_ml_feature_importance.csv',
                    directory=_dir, float_fmt='%.6f')
        except Exception as _exc:
            _logger.debug('ml feature section skipped: %s', _exc)

        try:
            ml = getattr(sens, 'ml_sensitivity', None)
            if ml is not None and ml.loo_model_impact:
                df = pd.DataFrame([
                    {'Model': k, 'LOO_Impact': v, 'Contribution_CV': ml.model_contribution_cv.get(k, 0)}
                    for k, v in sorted(ml.loo_model_impact.items(), key=lambda x: x[1], reverse=True)
                ]).set_index('Model')
                saved['ml_model_impact'] = self._save_csv(
                    df, 'sensitivity_ml_model_impact.csv',
                    directory=_dir, float_fmt='%.6f')
        except Exception as _exc:
            _logger.debug('ml model section skipped: %s', _exc)

        # ER Sensitivity
        try:
            er = getattr(sens, 'er_sensitivity', None)
            if er is not None and er.criterion_belief_sensitivity:
                df = pd.DataFrame([
                    {'Criterion': k, 'Belief_Sensitivity': v}
                    for k, v in sorted(
                        er.criterion_belief_sensitivity.items(),
                        key=lambda x: x[1], reverse=True
                    )
                ]).set_index('Criterion')
                df['Level'] = df['Belief_Sensitivity'].apply(
                    lambda x: 'High' if x > 0.3 else ('Medium' if x > 0.15 else 'Low'))
                saved['er_criterion_sensitivity'] = self._save_csv(
                    df, 'sensitivity_er_criterion.csv', directory=_dir, float_fmt='%.6f')
        except Exception as _exc:
            _logger.debug('er criterion section skipped: %s', _exc)

        try:
            er = getattr(sens, 'er_sensitivity', None)
            if er is not None and er.utility_interval_width:
                df = pd.DataFrame([
                    {'Entity': k, 'Utility_Interval_Width': v,
                     'Utility_Sensitivity': er.utility_sensitivity.get(k, 0)}
                    for k, v in sorted(
                        er.utility_interval_width.items(),
                        key=lambda x: x[1], reverse=True
                    )
                ]).set_index('Entity')
                saved['er_utility_sensitivity'] = self._save_csv(
                    df, 'sensitivity_er_utility.csv', directory=_dir, float_fmt='%.6f')
        except Exception as _exc:
            _logger.debug('er utility section skipped: %s', _exc)

        try:
            er = getattr(sens, 'er_sensitivity', None)
            if er is not None and er.cross_level_consistency:
                df = pd.DataFrame([
                    {'Level': k, 'Spearman_Rho': v}
                    for k, v in sorted(er.cross_level_consistency.items())
                ]).set_index('Level')
                saved['er_cross_level'] = self._save_csv(
                    df, 'sensitivity_er_cross_level.csv', directory=_dir, float_fmt='%.6f')
        except Exception as _exc:
            _logger.debug('er cross-level section skipped: %s', _exc)

        # Summary JSON
        try:
            ml = getattr(sens, 'ml_sensitivity', None)
            er = getattr(sens, 'er_sensitivity', None)
            summary = {
                'overall_robustness': getattr(sens, 'overall_robustness', 0),
                'ml_robustness': getattr(ml, 'overall_robustness', None),
                'er_robustness': getattr(er, 'overall_er_robustness', None),
                'ml_temporal_stability': getattr(ml, 'temporal_prediction_stability', None),
                'ml_interval_width_cv': getattr(ml, 'interval_width_cv', None),
                'er_mean_entropy': getattr(er, 'mean_belief_entropy', None),
                'er_high_uncertainty_entities': getattr(er, 'high_uncertainty_entities', []),
            }
            saved['summary'] = self._save_json(summary, 'sensitivity_summary.json',
                                               directory=_dir)
        except Exception as _exc:
            _logger.debug('summary section skipped: %s', _exc)

        return saved

    # ==================================================================
    #  7. ER UNCERTAINTY
    # ==================================================================

    def save_er_uncertainty(self, ranking_result: Any,
                            provinces: List[str]) -> Optional[str]:
        """
        Save Evidence Reasoning uncertainty metrics.

        Parameters
        ----------
        ranking_result : RankingResult
            Results containing the ER uncertainty dataframe.
        provinces : List[str]
            List of province names for indexing.

        Returns
        -------
        str, optional
            The absolute path to the saved CSV file, or None if failed.
        """
        try:
            unc = ranking_result.er_result.uncertainty.copy()
            unc.index.name = 'Province'
            return self._save_csv(unc, 'prediction_uncertainty_er.csv',
                                    directory=self.mcdm_dir, float_fmt='%.6f')
        except Exception as _exc:
            _logger.debug('er_uncertainty skipped: %s', _exc)
            return None

    # ==================================================================
    #  8. CRITERION WEIGHTS  [REMOVED — redundant with per-year all-years
    #     matrices; panel-level snapshot caused value discrepancy vs the
    #     correct per-year critic_weights_YYYY.csv files]
    # ==================================================================

    # ==================================================================
    #  9. EXECUTION SUMMARY  [REMOVED — summary/ phase removed]
    # ==================================================================

    # ==================================================================
    # 10. CONFIG SNAPSHOT  [REMOVED — summary/ phase removed]
    # ==================================================================

    # ==================================================================
    # 11. METHOD WEIGHTS (panel-level critic_weights.csv)  [REMOVED —
    #     panel-level snapshot redundant and inconsistent with per-year
    #     critic_weights_YYYY.csv files]
    # ==================================================================

    # ==================================================================
    # 13. MC PROVINCE STATS — Monte-Carlo rank uncertainty per province
    # ==================================================================

    def save_mc_province_stats(self, weights: Dict[str, Any]) -> Optional[str]:
        """
        Write Monte-Carlo rank-uncertainty statistics per province.

        Parameters
        ----------
        weights : Dict[str, Any]
            The weights dictionary containing 'mc_province_stats'.

        Returns
        -------
        str, optional
            The absolute path to the saved CSV file, or None if no data 
            was found.
        """
        try:
            mps = weights.get('mc_province_stats', {})
            if not mps:
                return None

            mean_r   = mps.get('province_mean_rank', {})
            std_r    = mps.get('province_std_rank', {})
            prob_t1  = mps.get('province_prob_top1', {})
            prob_tk  = mps.get('province_prob_topK', {})

            all_provinces = sorted(set(mean_r) | set(std_r))
            rows = []
            for prov in all_provinces:
                mr = float(mean_r.get(prov, 0.0))
                sr = float(std_r.get(prov, 0.0))
                rows.append({
                    'Province':        prov,
                    'MC_Mean_Rank':    mr,
                    'MC_Std_Rank':     sr,
                    'MC_CV_Rank':      sr / mr if mr > 0 else 0.0,
                    'MC_Prob_Top1':    float(prob_t1.get(prov, 0.0)),
                    'MC_Prob_TopK':    float(prob_tk.get(prov, 0.0)),
                })

            df = pd.DataFrame(rows).set_index('Province')
            df = df.sort_values('MC_Mean_Rank')
            df['MC_Nominal_Rank'] = range(1, len(df) + 1)

            # Win-rate matrix (optional)
            win_mat = mps.get('rank_win_matrix')
            if win_mat is not None and hasattr(win_mat, 'to_csv'):
                win_path = Path(self.weighting_dir) / 'mc_rank_win_matrix.csv'
                win_mat.to_csv(win_path, float_format='%.4f')
                self._record(str(win_path))

            return self._save_csv(
                df, 'mc_province_rankings.csv',
                directory=self.weighting_dir, float_fmt='%.4f')
        except Exception as _exc:
            _logger.debug('mc_province_stats skipped: %s', _exc)
            return None

    # ==================================================================
    # 14. ALL-YEARS RANKINGS
    # ==================================================================

    def save_rankings_all_years(
        self,
        multi_year_results: Dict[int, Any],
        provinces: List[str],
    ) -> Dict[str, str]:
        """
        Write Province x Year matrices for composite scores and ranks.

        Parameters
        ----------
        multi_year_results : Dict[int, Any]
            Dictionary mapping year to ranking results.
        provinces : List[str]
            List of province names for indexing.

        Returns
        -------
        Dict[str, str]
            Dictionary mapping 'scores' and 'ranks' to their absolute paths.
        """
        saved: Dict[str, str] = {}
        if not multi_year_results:
            return saved

        years = sorted(multi_year_results.keys())

        # ── Score and rank Province × Year matrices ─────────────────────
        try:
            score_data: Dict[int, pd.Series] = {}
            rank_data:  Dict[int, pd.Series] = {}
            for yr in years:
                yr_res = multi_year_results[yr]
                fs = yr_res.final_scores if hasattr(yr_res, 'final_scores') else None
                fr = yr_res.final_ranking if hasattr(yr_res, 'final_ranking') else None
                if fs is not None:
                    score_data[yr] = fs
                if fr is not None:
                    rank_data[yr] = fr

            if score_data:
                score_df = pd.DataFrame(score_data)
                score_df.index.name = 'Province'
                score_df.columns.name = 'Year'
                score_df['Mean_Score']     = score_df.mean(axis=1)
                score_df['Trend']          = score_df[years].apply(
                    lambda row: float(np.polyfit(range(len(years)), row.values, 1)[0]),
                    axis=1)
                saved['scores'] = self._save_csv(
                    score_df, 'rankings_all_years.csv',
                    directory=self.mcdm_dir, float_fmt='%.4f')

            if rank_data:
                rank_df = pd.DataFrame(rank_data)
                rank_df.index.name = 'Province'
                rank_df.columns.name = 'Year'
                rank_df['Mean_Rank'] = rank_df[years].mean(axis=1).round(2)
                rank_df['Rank_Volatility'] = rank_df[years].std(axis=1).round(2)
                best_yr = rank_df[years].idxmin(axis=1)
                rank_df['Best_Year'] = best_yr
                saved['ranks'] = self._save_csv(
                    rank_df, 'ranks_all_years.csv',
                    directory=self.mcdm_dir, float_fmt='%.2f')
        except Exception as _exc:
            _logger.debug('all-years score/rank matrix skipped: %s', _exc)

        # ── Long-format criterion-level ER utilities ─────────────────────
        try:
            long_rows = []
            for yr in years:
                yr_res = multi_year_results[yr]
                er_res = getattr(yr_res, 'er_result', None)
                if er_res is None:
                    continue
                crit_beliefs = getattr(er_res, 'criterion_beliefs', {})
                for prov, crit_dict in crit_beliefs.items():
                    for crit_id, bd in crit_dict.items():
                        long_rows.append({
                            'Year':      yr,
                            'Province':  prov,
                            'Criterion': crit_id,
                            'ER_Utility': float(bd.average_utility()),
                            'Belief_Entropy': float(bd.belief_entropy()),
                        })
            if long_rows:
                long_df = pd.DataFrame(long_rows)
                saved['criterion_er'] = self._save_csv(
                    long_df, 'criterion_er_scores_all_years.csv',
                    directory=self.mcdm_dir, float_fmt='%.4f')
        except Exception as _exc:
            _logger.debug('criterion ER long-format skipped: %s', _exc)

        return saved

    # ==================================================================
    # 15. BELIEF DISTRIBUTIONS
    # ==================================================================

    def save_belief_distributions(
        self, ranking_result: Any, provinces: List[str]
    ) -> Optional[str]:
        """
        Write per-province, per-criterion belief distributions.

        Exports the belief degrees for each grade from the Stage 1 ER 
        aggregation, providing visibility into the evidence structure.

        Parameters
        ----------
        ranking_result : RankingResult
            The results containing the ER belief matrices.
        provinces : List[str]
            List of province names for iteration.

        Returns
        -------
        str, optional
            The absolute path to the saved CSV file, or None if no 
            distributions were found.
        """
        try:
            er_res = getattr(ranking_result, 'er_result', None)
            if er_res is None:
                return None
            crit_beliefs = getattr(er_res, 'criterion_beliefs', {})
            if not crit_beliefs:
                return None

            # Infer grade labels from first entry
            first_prov  = next(iter(crit_beliefs))
            first_crit  = next(iter(crit_beliefs[first_prov]))
            first_bd    = crit_beliefs[first_prov][first_crit]
            n_grades    = len(first_bd.degrees)
            grade_cols  = [f'Grade_{g+1}' for g in range(n_grades)]

            rows = []
            for prov in provinces:
                if prov not in crit_beliefs:
                    continue
                for crit_id, bd in sorted(crit_beliefs[prov].items()):
                    row: Dict[str, Any] = {'Province': prov, 'Criterion': crit_id}
                    for g_idx, g_col in enumerate(grade_cols):
                        row[g_col] = float(bd.degrees[g_idx]) if g_idx < len(bd.degrees) else 0.0
                    row['Unassigned']     = float(getattr(bd, 'unassigned', 0.0))
                    row['Belief_Entropy'] = float(bd.belief_entropy())
                    row['Avg_Utility']    = float(bd.average_utility())
                    rows.append(row)

            if not rows:
                return None

            df = pd.DataFrame(rows)
            df = df.sort_values(['Province', 'Criterion']).reset_index(drop=True)
            df.index.name = 'RowID'
            return self._save_csv(
                df, 'belief_distributions.csv',
                directory=self.mcdm_dir, float_fmt='%.6f')
        except Exception as _exc:
            _logger.debug('belief distributions skipped: %s', _exc)
            return None

    # ==================================================================
    # 16. MCDM COMPOSITE COMPARISON (all methods + ER, one row per province)
    # ==================================================================

    def save_mcdm_composite_comparison(
        self, ranking_result: Any, provinces: List[str]
    ) -> Optional[str]:
        """
        Write a single wide table with composite (averaged across criteria)
        scores and ranks for every MCDM method plus the final aggregated score, and
        Spearman rank correlations vs. final aggregated rank.

        File produced
        -------------
        mcdm/mcdm_composite_scores.csv
        """
        try:
            active_provinces = (
                list(ranking_result.final_ranking.index)
                if hasattr(ranking_result.final_ranking, 'index')
                else provinces
            )

            # Aggregate per-criterion method scores → composite per method
            method_composites: Dict[str, pd.Series] = {}
            for crit_id, method_scores in ranking_result.criterion_method_scores.items():
                for method, series in method_scores.items():
                    s = series.reindex(active_provinces) if hasattr(series, 'reindex') else pd.Series(
                        np.asarray(series), index=active_provinces)
                    if method not in method_composites:
                        method_composites[method] = s
                    else:
                        method_composites[method] = method_composites[method].add(s, fill_value=0.0)

            n_criteria = max(
                len(ranking_result.criterion_method_scores), 1)
            for method in list(method_composites.keys()):
                method_composites[method] = method_composites[method] / n_criteria

            df = pd.DataFrame(method_composites, index=active_provinces)
            df.index.name = 'Province'

            # Rank columns
            score_cols = list(df.columns)
            for col in score_cols:
                df[f'{col}_Rank'] = df[col].rank(ascending=False, method='min').astype(int)

            # Final aggregated score + rank
            agg_scores = ranking_result.final_scores.reindex(active_provinces)
            df['Composite_Score'] = agg_scores.values
            df['Composite_Rank']  = ranking_result.final_ranking.reindex(active_provinces).values

            # Summary stats across method ranks
            rank_cols = [f'{c}_Rank' for c in score_cols]
            df['Mean_Method_Score'] = df[score_cols].mean(axis=1)
            df['Rank_Range']        = df[rank_cols].max(axis=1) - df[rank_cols].min(axis=1)

            # Spearman correlation of each method vs. aggregated rank
            agg_rank = df['Composite_Rank']
            from scipy.stats import spearmanr
            spearman_row: Dict[str, float] = {}
            for col in score_cols:
                r_col = f'{col}_Rank'
                rho, _ = spearmanr(df[r_col], agg_rank)
                spearman_row[col] = round(float(rho), 4)
            df['Spearman_vs_Agg'] = df[score_cols].apply(
                lambda row: float(np.mean([spearman_row.get(c, 0) for c in score_cols])), axis=1)

            df = df.sort_values('Composite_Rank').reset_index()
            df.index = df.index + 1
            df.index.name = 'Position'

            return self._save_csv(
                df, 'mcdm_composite_scores.csv',
                directory=self.mcdm_dir, float_fmt='%.4f')
        except Exception as _exc:
            _logger.debug('mcdm composite comparison skipped: %s', _exc)
            return None

    # ==================================================================
    # 17. INDIVIDUAL MODEL PREDICTIONS
    # ==================================================================

    def save_individual_model_predictions(
        self, forecast_result: Any
    ) -> Optional[str]:
        """
        Write a wide table with each base model's predictions.

        Includes the Super Learner ensemble point forecast and the conformal 
        prediction interval bounds for comparison.

        Parameters
        ----------
        forecast_result : UnifiedForecastResult
            The results containing model-specific predictions.

        Returns
        -------
        str, optional
            The absolute path to the saved CSV file, or None if failed.
        """
        try:
            tinfo = forecast_result.training_info or {}

            # Base model predictions stored under training_info['model_predictions']
            model_preds = tinfo.get('model_predictions', {})
            if not model_preds and not hasattr(forecast_result, 'predictions'):
                return None

            ensemble_preds = forecast_result.predictions
            if ensemble_preds is None or ensemble_preds.empty:
                return None

            index = ensemble_preds.index

            df = pd.DataFrame(index=index)
            df.index.name = 'Entity'

            # Individual base model columns
            for model_name, pred_arr in model_preds.items():
                try:
                    arr = np.asarray(pred_arr).flatten()
                    if len(arr) == len(index):
                        df[f'{model_name}_pred'] = arr
                except Exception as _exc:
                    _logger.debug('model column %s skipped: %s', model_name, _exc)

            # Ensemble / Meta-Learner column
            if not ensemble_preds.empty and ensemble_preds.shape[1] >= 1:
                df['MetaLearner_pred'] = ensemble_preds.iloc[:, 0].values

            # Conformal prediction intervals
            try:
                intervals = forecast_result.prediction_intervals
                if intervals:
                    lower = intervals.get('lower')
                    upper = intervals.get('upper')
                    if lower is not None and not lower.empty:
                        df['CI_Lower'] = lower.iloc[:, 0].values
                    if upper is not None and not upper.empty:
                        df['CI_Upper'] = upper.iloc[:, 0].values
                    if 'CI_Lower' in df.columns and 'CI_Upper' in df.columns:
                        df['CI_Width'] = df['CI_Upper'] - df['CI_Lower']
            except Exception as _exc:
                _logger.debug('conformal interval columns skipped: %s', _exc)

            # Model weights for reference
            weights = forecast_result.model_contributions or {}
            weight_row = {k: round(v, 6) for k, v in weights.items()}
            df.attrs['model_weights'] = str(weight_row)

            return self._save_csv(
                df, 'individual_model_predictions.csv',
                directory=self.forecasting_dir, float_fmt='%.4f')
        except Exception as _exc:
            _logger.debug('individual model predictions skipped: %s', _exc)
            return None

    # ==================================================================
    # 18. PERTURBATION DETAIL — sensitivity × perturbation level matrix
    # ==================================================================

    def save_perturbation_detail(
        self, analysis_results: Dict[str, Any]
    ) -> Optional[str]:
        """
        Persist Monte-Carlo perturbation analysis results.

        Handles both tidy alternative-wise summaries and complex 
        Criterion x Level matrices from the sensitivity analysis engine.

        Parameters
        ----------
        analysis_results : Dict[str, Any]
            Dictionary containing sensitivity perturbation data.

        Returns
        -------
        str, optional
            The absolute path to the saved CSV file, or None if failed.
        """
        try:
            sens = analysis_results.get('sensitivity')
            if sens is None:
                return None

            # Try common attribute names
            pert = (
                getattr(sens, 'perturbation_analysis', None)
                or getattr(sens, 'weight_perturbation', None)
                or getattr(sens, 'perturbation_detail', None)
            )
            if pert is None:
                return None

            # ── Shape 1: summary dict from SensitivityAnalysis ──────────
            if (
                isinstance(pert, dict)
                and 'mean_rank' in pert
                and 'std_rank' in pert
            ):
                import numpy as _np
                mean_rk = _np.asarray(pert['mean_rank'])
                std_rk  = _np.asarray(pert['std_rank'])
                rk_range = _np.asarray(pert.get('rank_range', std_rk * 0))
                n = len(mean_rk)

                df = pd.DataFrame({
                    'Mean_Rank':  mean_rk,
                    'Std_Rank':   std_rk,
                    'Rank_Range': rk_range,
                })
                df.index.name = 'Alternative'
                df['Stability_Score'] = 1.0 - (
                    std_rk / (std_rk.max() + 1e-12)
                )
                return self._save_csv(
                    df, 'perturbation_detail.csv',
                    directory=self.sensitivity_dir, float_fmt='%.4f')

            # ── Shape 2: DataFrame or nested criterion→level dict ───────
            if isinstance(pert, pd.DataFrame):
                df = pert.copy()
            elif isinstance(pert, dict):
                df = pd.DataFrame(pert).T
            else:
                return None

            df.index.name = 'Criterion'

            # Numeric columns only for summary stats
            num_cols = df.select_dtypes(include='number').columns
            if len(num_cols):
                df['Mean_Correlation']  = df[num_cols].mean(axis=1)
                df['Min_Correlation']   = df[num_cols].min(axis=1)
                df['Sensitivity_Score'] = 1 - df['Mean_Correlation']
                df['Sensitivity_Rank']  = df['Sensitivity_Score'].rank(
                    ascending=False, method='min').astype(int)

            return self._save_csv(
                df, 'perturbation_detail.csv',
                directory=self.sensitivity_dir, float_fmt='%.4f')
        except Exception as _exc:
            _logger.debug('perturbation detail skipped: %s', _exc)
            return None

    # ==================================================================
    # 19. PER-YEAR CRITIC WEIGHTS
    # ==================================================================

    def save_weights_all_years(
        self, weight_all_years: Dict[int, Any]
    ) -> Dict[str, str]:
        """
        Persist per-year CRITIC weights and global summaries.

        Parameters
        ----------
        weight_all_years : Dict[int, Any]
            Dictionary mapping year to calculated weights.

        Returns
        -------
        Dict[str, str]
            Dictionary mapping artifact keys to their absolute file paths.
        """
        saved: Dict[str, str] = {}
        if not weight_all_years:
            return saved

        years = sorted(weight_all_years.keys())

        # ── Per-year individual files ────────────────────────────────────
        for yr in years:
            try:
                yw = weight_all_years[yr]
                sc_list     = yw.get('subcriteria', [])
                global_sc   = yw.get('global_sc_weights', {})
                crit_w      = yw.get('criterion_weights', {})
                details     = yw.get('details', {})
                level1      = details.get('level1', {})
                groups      = yw.get('criteria_groups', {})

                # Build SC → criterion lookup
                sc_to_crit: Dict[str, str] = {}
                for cid, sc_cols in groups.items():
                    for sc in sc_cols:
                        sc_to_crit[sc] = cid

                rows = []
                for sc in sc_list:
                    cid   = sc_to_crit.get(sc, '')
                    l1c   = level1.get(cid, {}).get('local_sc_weights', {})
                    rows.append({
                        'Subcriteria':          sc,
                        'Criterion':            cid,
                        'Critic_Local_Weight':  float(l1c.get(sc, 0.0)),
                        'Critic_Global_Weight': float(global_sc.get(sc, 0.0)),
                        'Critic_Crit_Weight':   float(crit_w.get(cid, 0.0)),
                    })

                if not rows:
                    continue

                df = pd.DataFrame(rows).set_index('Subcriteria')
                # Enforce explicit column order
                df = df[['Criterion', 'Critic_Local_Weight',
                          'Critic_Global_Weight', 'Critic_Crit_Weight']]
                df['Rank'] = df['Critic_Global_Weight'].rank(
                    ascending=False, method='min').astype(int)

                fname = f'critic_weights_{yr}.csv'
                saved[f'year_{yr}'] = self._save_csv(
                    df, fname, directory=self.weighting_dir, float_fmt='%.6f')
            except Exception as _exc:
                _logger.debug('per-year weights year %d skipped: %s', yr, _exc)

        # ── SC × Year global-weight matrix ───────────────────────────────
        try:
            sc_year_data: Dict[int, Dict[str, float]] = {}
            all_scs: List[str] = []
            for yr in years:
                gw = weight_all_years[yr].get('global_sc_weights', {})
                sc_year_data[yr] = gw
                for sc in gw:
                    if sc not in all_scs:
                        all_scs.append(sc)

            sc_df = pd.DataFrame(
                {yr: [sc_year_data[yr].get(sc, float('nan')) for sc in all_scs]
                 for yr in years},
                index=all_scs,
            )
            sc_df.index.name  = 'Subcriteria'
            sc_df.columns.name = 'Year'
            sc_df['Mean_Weight'] = sc_df[years].mean(axis=1)
            sc_df['StdDev']      = sc_df[years].std(axis=1)
            saved['sc_matrix'] = self._save_csv(
                sc_df, 'sc_global_weights_all_years.csv',
                directory=self.weighting_dir, float_fmt='%.6f')
        except Exception as _exc:
            _logger.debug('SC weight matrix skipped: %s', _exc)

        # ── Criterion × Year weight matrix ───────────────────────────────
        try:
            crit_year_data: Dict[int, Dict[str, float]] = {}
            all_crits: List[str] = []
            for yr in years:
                cw = weight_all_years[yr].get('criterion_weights', {})
                crit_year_data[yr] = cw
                for c in sorted(cw):
                    if c not in all_crits:
                        all_crits.append(c)
            all_crits.sort()

            crit_df = pd.DataFrame(
                {yr: [crit_year_data[yr].get(c, float('nan')) for c in all_crits]
                 for yr in years},
                index=all_crits,
            )
            crit_df.index.name  = 'Criterion'
            crit_df.columns.name = 'Year'
            crit_df['Mean_Weight'] = crit_df[years].mean(axis=1)
            crit_df['StdDev']      = crit_df[years].std(axis=1)
            saved['crit_matrix'] = self._save_csv(
                crit_df, 'critic_criterion_weights_all_years.csv',
                directory=self.weighting_dir, float_fmt='%.6f')
        except Exception as _exc:
            _logger.debug('criterion weight matrix skipped: %s', _exc)

        # ── SC × Year LOCAL-weight matrix ─────────────────────────────────
        # Complements sc_global_weights_all_years.csv (global SC weights).
        # Each cell is the CRITIC within-group local weight for that SC in
        # that year (sums to 1 within each criterion group, not globally).
        try:
            sc_local_year_data: Dict[int, Dict[str, float]] = {}
            all_scs_local: List[str] = []
            for yr in years:
                yw = weight_all_years[yr]
                details_yr = yw.get('details', {})
                level1_yr  = details_yr.get('level1', {})
                groups_yr  = yw.get('criteria_groups', {})
                sc_local: Dict[str, float] = {}
                for cid, sc_cols in groups_yr.items():
                    l1c = level1_yr.get(cid, {}).get('local_sc_weights', {})
                    for sc in sc_cols:
                        sc_local[sc] = float(l1c.get(sc, float('nan')))
                sc_local_year_data[yr] = sc_local
                for sc in sc_local:
                    if sc not in all_scs_local:
                        all_scs_local.append(sc)

            local_df = pd.DataFrame(
                {yr: [sc_local_year_data[yr].get(sc, float('nan'))
                      for sc in all_scs_local]
                 for yr in years},
                index=all_scs_local,
            )
            local_df.index.name  = 'Subcriteria'
            local_df.columns.name = 'Year'
            local_df['Mean_Weight'] = local_df[years].mean(axis=1)
            local_df['StdDev']      = local_df[years].std(axis=1)
            saved['sc_local_matrix'] = self._save_csv(
                local_df, 'sc_local_weights_all_years.csv',
                directory=self.weighting_dir, float_fmt='%.6f')
        except Exception as _exc:
            _logger.debug('SC local weight matrix skipped: %s', _exc)

        return saved

    # ==================================================================
    # 20. PER-CRITERION MCDM RANKING FILES  (9 CSVs, all years)
    # ==================================================================

    def save_method_scores_all_years(
        self, multi_year_results: Dict[int, Any]
    ) -> Dict[str, str]:
        """
        Persist per-criterion MCDM ranking files spanning all years.

        Parameters
        ----------
        multi_year_results : Dict[int, Any]
            Dictionary mapping year to ranking results.

        Returns
        -------
        Dict[str, str]
            Dictionary mapping criterion ID to absolute file path.
        """
        saved: Dict[str, str] = {}
        if not multi_year_results:
            _logger.warning('[DEBUG] save_method_scores_all_years: multi_year_results is empty')
            return saved

        _logger.info(f'[DEBUG] save_method_scores_all_years: processing {len(multi_year_results)} years')
        _METHODS = ['TOPSIS', 'VIKOR', 'PROMETHEE', 'COPRAS', 'EDAS', 'Base']
        _RANK_COLS = [f'{m}_Rank' for m in _METHODS] + ['Composite_Rank']
        years = sorted(multi_year_results.keys())

        # Accumulate rows per criterion and for composite
        crit_rows: Dict[str, List[Dict]] = {}
        composite_rows: List[Dict] = []

        for yr in years:
            try:
                yr_res = multi_year_results[yr]
                _logger.info(f'[DEBUG] Year {yr}: processing ranking result')
                method_scores = getattr(yr_res, 'criterion_method_scores', {})
                method_ranks  = getattr(yr_res, 'criterion_method_ranks', {})
                _logger.info(f'[DEBUG] Year {yr}: method_scores keys={list(method_scores.keys())}, method_ranks keys={list(method_ranks.keys())}')
                er_res        = getattr(yr_res, 'er_result', None)
                crit_beliefs  = getattr(er_res, 'criterion_beliefs', {}) if er_res else {}
                final_ranking = getattr(yr_res, 'final_ranking', None)
                final_scores  = getattr(yr_res, 'final_scores', None)

                if not method_scores:
                    _logger.warning(f'[DEBUG] Year {yr}: SKIPPED (method_scores is empty)')
                    continue

                _logger.info(f'[DEBUG] Year {yr}: Processing {len(method_scores)} criteria')

                # ── Per-criterion ranking rows ────────────────────────────
                for crit_id in sorted(method_scores):
                    if crit_id not in crit_rows:
                        crit_rows[crit_id] = []

                    crit_data       = method_scores[crit_id]
                    crit_rank_data  = method_ranks.get(crit_id, {})

                    first_series = next(iter(crit_data.values()), None)
                    if first_series is None:
                        continue
                    prov_list = (
                        list(first_series.index)
                        if hasattr(first_series, 'index')
                        else []
                    )

                    for prov in prov_list:
                        row: Dict[str, Any] = {'Year': yr, 'Province': prov}
                        for method in _METHODS:
                            rank_series = crit_rank_data.get(method)
                            if rank_series is not None and hasattr(rank_series, 'loc') and prov in rank_series.index:
                                v = rank_series.loc[prov]
                                row[f'{method}_Rank'] = int(v) if not pd.isna(v) else pd.NA
                            else:
                                row[f'{method}_Rank'] = pd.NA
                        crit_rows[crit_id].append(row)

                # ── Composite ranking rows ────────────────────────────────
                # Active province list
                if final_ranking is not None and hasattr(final_ranking, 'index'):
                    active_provinces = list(final_ranking.index)
                elif final_scores is not None and hasattr(final_scores, 'index'):
                    active_provinces = list(final_scores.index)
                else:
                    first_crit = next(iter(method_scores.values()), {})
                    first_s = next(iter(first_crit.values()), None)
                    active_provinces = (
                        list(first_s.index)
                        if first_s is not None and hasattr(first_s, 'index')
                        else []
                    )

                # Sum scores across criteria per method → composite score → rank
                method_composite_scores: Dict[str, pd.Series] = {}
                for method in _METHODS:
                    sums = pd.Series(0.0, index=active_provinces)
                    cnts = pd.Series(0,   index=active_provinces)
                    for _crit_id, crit_data in method_scores.items():
                        series = crit_data.get(method)
                        if series is None:
                            continue
                        for prov in active_provinces:
                            if hasattr(series, 'loc') and prov in series.index:
                                val = float(series.loc[prov])
                                if not np.isnan(val):
                                    sums[prov]  += val
                                    cnts[prov]  += 1
                    composite = sums / cnts.replace(0, float('nan'))
                    method_composite_scores[method] = composite

                for method in _METHODS:
                    s = method_composite_scores[method]
                    # Rank composite: higher average score = better rank
                    method_composite_scores[f'{method}_Rank'] = s.rank(
                        ascending=False, method='min', na_option='bottom'
                    ).astype('Int64')

                for prov in active_provinces:
                    row = {'Year': yr, 'Province': prov}
                    for method in _METHODS:
                        rk = method_composite_scores[f'{method}_Rank']
                        v = rk.loc[prov] if prov in rk.index else pd.NA
                        row[f'{method}_Rank'] = int(v) if not pd.isna(v) else pd.NA
                    comp_v = final_ranking.loc[prov] if prov in final_ranking.index else pd.NA
                    row['Composite_Rank'] = int(comp_v) if not pd.isna(comp_v) else pd.NA
                    composite_rows.append(row)

            except Exception as _exc:
                _logger.debug('ranking files for year %d skipped: %s', yr, _exc)

        # ── Write per-criterion ranking files ─────────────────────────────
        for crit_id, rows in crit_rows.items():
            if not rows:
                continue
            df = pd.DataFrame(rows)
            df = df[['Year', 'Province'] + _RANK_COLS]
            df = df.sort_values(['Year', 'Province']).reset_index(drop=True)
            df.index.name = 'RowID'
            fname = f'mcdm_criteria_{crit_id}_ranking.csv'
            saved[crit_id] = self._save_csv(
                df, fname, directory=self.ranking_dir, float_fmt='%.0f')

        # ── Write composite ranking file ───────────────────────────────────
        if composite_rows:
            df = pd.DataFrame(composite_rows)
            df = df[['Year', 'Province'] + _RANK_COLS]
            df = df.sort_values(['Year', 'Province']).reset_index(drop=True)
            df.index.name = 'RowID'
            saved['composite'] = self._save_csv(
                df, 'mcdm_scores_composite_ranking.csv',
                directory=self.ranking_dir, float_fmt='%.0f')

        _logger.info(f'[DEBUG] save_method_scores_all_years complete: saved {len(saved)} files (criteria: {list(saved.keys())})')
        return saved

    def save_temporal_stability(self, temporal_result: Any) -> Optional[str]:
        """
        Save temporal stability analysis results.

        Persists aggregate metrics and rolling window timelines to 
        quantify the consistency of criteria weights over time.

        Parameters
        ----------
        temporal_result : TemporalStabilityResult
            The result object from the stability analyzer.

        Returns
        -------
        str, optional
            The absolute path to the main summary CSV file, or None 
            if failed.
        """
        if temporal_result is None:
            return None

        saved_files = []

        try:
            # Summary statistics
            summary_data = {
                'Metric': [
                    'Spearman_Rho_Mean',
                    'Spearman_Rho_Std',
                    'Kendalls_W',
                    'Year_Min',
                    'Year_Max',
                    'N_Windows',
                    'N_Pairs',
                ],
                'Value': [
                    float(temporal_result.spearman_rho_mean),
                    float(temporal_result.spearman_rho_std),
                    float(temporal_result.kendalls_w),
                    temporal_result.year_range[0],
                    temporal_result.year_range[1],
                    len(temporal_result.rolling_timeline) if temporal_result.rolling_timeline else 0,
                    len(temporal_result.spearman_rho_rolling),
                ],
            }
            df_summary = pd.DataFrame(summary_data)
            path_summary = self._save_csv(
                df_summary,
                'temporal_stability_summary.csv',
                directory=self.weighting_dir,
                float_fmt='%.6g'
            )
            saved_files.append(path_summary)

            # Per-criterion CV
            cv_data = {
                'Criterion': list(temporal_result.coefficient_variation.keys()),
                'Coefficient_Variation': list(temporal_result.coefficient_variation.values()),
            }
            df_cv = pd.DataFrame(cv_data).sort_values('Criterion').reset_index(drop=True)
            path_cv = self._save_csv(
                df_cv,
                'temporal_stability_cv.csv',
                directory=self.weighting_dir,
                float_fmt='%.6g'
            )
            saved_files.append(path_cv)

            # Rolling window timeline (if available)
            if temporal_result.rolling_timeline:
                df_rolling = pd.DataFrame(temporal_result.rolling_timeline)
                path_rolling = self._save_csv(
                    df_rolling,
                    'temporal_stability_rolling_window.csv',
                    directory=self.weighting_dir,
                    float_fmt='%.6g'
                )
                saved_files.append(path_rolling)

            return path_summary  # Return main summary file

        except Exception as exc:
            _logger.warning(f'save_temporal_stability failed: {exc}')
            return None

    def save_sensitivity_analysis(self, sensitivity_result: Any) -> Optional[str]:
        """
        Save comprehensive sensitivity analysis results.

        Exports robustness scores, per-criterion sensitivities, and rank 
        disruption statistics across multiple perturbation tiers.

        Parameters
        ----------
        sensitivity_result : SensitivityResult
            The result object containing multi-tier metrics.

        Returns
        -------
        str, optional
            The absolute path to the main summary CSV file, or None 
            if failed.
        """
        if sensitivity_result is None:
            return None

        saved_files = []

        try:
            # Tier robustness summary
            robustness_data = {
                'Tier': list(sensitivity_result.tier_robustness.keys()),
                'Robustness_Score': list(sensitivity_result.tier_robustness.values()),
            }
            df_robustness = pd.DataFrame(robustness_data).sort_values('Tier').reset_index(drop=True)
            path_robustness = self._save_csv(
                df_robustness,
                'sensitivity_analysis_summary.csv',
                directory=self.weighting_dir,
                float_fmt='%.6g'
            )
            saved_files.append(path_robustness)

            # Per-criterion sensitivity per tier
            criteria_rows = []
            for criterion in sensitivity_result.per_criterion_sensitivity.keys():
                row = {'Criterion': criterion}
                for tier, sensitivity in sensitivity_result.per_criterion_sensitivity[criterion].items():
                    row[f'Sensitivity_{tier}'] = float(sensitivity)
                criteria_rows.append(row)

            df_criteria = pd.DataFrame(criteria_rows).sort_values('Criterion').reset_index(drop=True)
            path_criteria = self._save_csv(
                df_criteria,
                'sensitivity_analysis_criteria.csv',
                directory=self.weighting_dir,
                float_fmt='%.6g'
            )
            saved_files.append(path_criteria)

            # Rank disruption statistics per tier
            disruption_rows = []
            for tier in sensitivity_result.rank_disruption_stats.keys():
                stats = sensitivity_result.rank_disruption_stats[tier]
                disruption_rows.append({
                    'Tier': tier,
                    'Mean_Disruption': float(stats.get('mean', 0.0)),
                    'Std_Disruption': float(stats.get('std', 0.0)),
                    'Max_Disruption': float(stats.get('max', 0.0)),
                    'Q95_Disruption': float(stats.get('q95', 0.0)),
                })

            df_disruption = pd.DataFrame(disruption_rows).sort_values('Tier').reset_index(drop=True)
            path_disruption = self._save_csv(
                df_disruption,
                'sensitivity_analysis_disruption.csv',
                directory=self.weighting_dir,
                float_fmt='%.6g'
            )
            saved_files.append(path_disruption)

            return path_robustness  # Return main summary file

        except Exception as exc:
            _logger.warning(f'save_sensitivity_analysis failed: {exc}')
            return None


__all__ = ['CsvWriter']
