# -*- coding: utf-8 -*-
"""
MCDM Ranking Result Visualization Package
==========================================

Professional visualization suite for analyzing and validating MCDM ranking results
across multiple methods and time periods.

Features:
  • Distribution analysis: 6 charts for individual MCDM method score distributions
  • Method agreement: Spearman rank correlation heatmap (6x6 methods matrix)
  • Concordance: Kendall's tau, Kendall's W for inter-method agreement
  • Comparison: Rank profile plots, boxplots, scatter plots
  • Robustness: Perturbation sensitivity analysis

Charts produced:
  fig09_distribution_TOPSIS.png
  fig09_distribution_VIKOR.png
  fig09_distribution_PROMETHEE.png
  fig09_distribution_COPRAS.png
  fig09_distribution_EDAS.png
  fig09_distribution_SAW.png
  fig10_method_agreement_matrix.png
  fig11_kendall_w_analysis.png
  fig12_rank_profiles.png
  fig13_method_boxplots.png
  fig14_method_scatter.png
  fig15_perturbation_sensitivity.png
"""

from __future__ import annotations

import logging
import numpy as np
import pandas as pd
from typing import Any, Dict, List, Optional, Tuple

from .base import (
    BasePlotter, HAS_MATPLOTLIB, HAS_SCIPY,
    PALETTE, CATEGORICAL_COLORS, GRADIENT_CMAPS, plt, sp_stats, gridspec,
)

_logger = logging.getLogger(__name__)

# Six MCDM methods generated by ranking pipeline (TOPSIS, VIKOR, PROMETHEE, COPRAS, EDAS + Base)
# Note: Config mentions SAW but pipeline actually computes Base (raw sum without weighting)
_METHODS = ['TOPSIS', 'VIKOR', 'PROMETHEE', 'COPRAS', 'EDAS', 'Base']
_METHOD_COLORS = {
    'TOPSIS': '#2E86AB',     # royal blue
    'VIKOR': '#A23B72',      # magenta
    'PROMETHEE': '#F18F01',  # amber
    'COPRAS': '#17B169',     # emerald
    'EDAS': '#C73E1D',       # crimson
    'Base': '#808080',       # gray (neutral baseline)
}


class MCDMRankingPlotter(BasePlotter):
    """
    Professional figures for validating and comparing MCDM ranking results.
    
    Analyzes results across 6 traditional MCDM methods (TOPSIS, VIKOR, PROMETHEE,
    COPRAS, EDAS, SAW) spanning multiple years (2011-2024) and multiple alternatives
    (63 provinces).
    
    Design philosophy:
      - Colorful, elegant, publication-quality visualizations
      - For comparison charts: clear axis scales for discrimination
      - For agreement/consensus charts: emphasis on agreement patterns
      - Mathematically sound, statistically rigorous
    """

    # ==================================================================
    #  FIG09 – Individual Method Distribution Scores (6 separate charts)
    # ==================================================================

    def plot_method_distribution_all_years(
        self,
        multi_year_results: Dict[int, Any],
        method: str = 'TOPSIS',
        title: Optional[str] = None,
        save_name: Optional[str] = None,
    ) -> Optional[str]:
        """
        Distribution of composite scores for a single MCDM method across all
        years (2011-2024) and all provinces.
        
        Visualizes:
          • Histogram with density overlay (KDE)
          • Rug plot showing individual values
          • Statistics box (mean, std, median)
          • Min-Max range shading
          
        One chart per method to enable direct visual comparison.

        Parameters
        ----------
        multi_year_results : Dict[int, Any]
            Dict mapping year -> HierarchicalRankingResult
        method : str
            One of: 'TOPSIS', 'VIKOR', 'PROMETHEE', 'COPRAS', 'EDAS', 'SAW'
        title : str, optional
            Chart title (auto-generated if None)
        save_name : str, optional
            Filename (auto-generated if None)

        Returns
        -------
        str | None
            Path to saved figure or None if matplotlib unavailable
        """
        if not HAS_MATPLOTLIB or not HAS_SCIPY:
            _logger.warning('plot_method_distribution_all_years: matplotlib/scipy unavailable')
            return None

        if method not in _METHODS:
            _logger.warning(f'Method {method} not in {_METHODS}')
            return None

        # Collect all composite scores for this method across years
        all_scores = []
        for yr in sorted(multi_year_results.keys()):
            result = multi_year_results[yr]
            method_scores = getattr(result, 'criterion_method_scores', {})
            
            # Average across criteria for composite score per method per province
            if method_scores:
                # Use pandas Series for proper index alignment across criteria
                criterion_series = []
                for crit_id in sorted(method_scores.keys()):
                    crit_data = method_scores[crit_id]
                    if method in crit_data:
                        series = crit_data[method]
                        # Ensure it's a pandas Series for proper alignment
                        if not isinstance(series, pd.Series):
                            series = pd.Series(series)
                        criterion_series.append(series)
                
                if criterion_series:
                    # Concatenate as DataFrame (columns = criteria), then compute mean per province (row)
                    try:
                        df_crit = pd.concat(criterion_series, axis=1)
                        composite = df_crit.mean(axis=1, skipna=True)  # Mean across criteria per province
                        # Extract non-NaN values
                        composite_values = composite.dropna().values
                        if len(composite_values) > 0:
                            all_scores.extend(composite_values)
                    except Exception as e:
                        _logger.debug(f'Aggregation failed for year {yr}: {e}')
                        continue

        if not all_scores:
            _logger.debug(f'plot_method_distribution_all_years({method}): No scores found')
            return None

        all_scores = np.array(all_scores)
        _logger.debug(f'plot_method_distribution_all_years({method}): {len(all_scores)} scores collected')
        
        # Create figure
        fig, ax = plt.subplots(figsize=(12, 7))
        
        # Histogram with KDE overlay
        n_bins = int(np.sqrt(len(all_scores)))
        ax.hist(all_scores, bins=n_bins, density=True, alpha=0.6, 
                color=_METHOD_COLORS[method], edgecolor='white', linewidth=0.5,
                label='Histogram')
        
        # KDE overlay
        if HAS_SCIPY and len(all_scores) > 10:
            from scipy.stats import gaussian_kde
            kde = gaussian_kde(all_scores)
            x_range = np.linspace(all_scores.min(), all_scores.max(), 200)
            ax.plot(x_range, kde(x_range), color='black', linewidth=2.0,
                   label='KDE', zorder=3)
        
        # Rug plot
        ax.plot(all_scores, np.zeros_like(all_scores), '|', 
               color=_METHOD_COLORS[method], markersize=10, markeredgewidth=1.0,
               alpha=0.5, label='Observations')
        
        # Min-max shading
        ax.axvspan(all_scores.min(), all_scores.max(), alpha=0.05, 
                  color=_METHOD_COLORS[method], zorder=1)
        
        # Statistics
        mean_val = np.nanmean(all_scores)
        median_val = np.nanmedian(all_scores)
        std_val = np.nanstd(all_scores)
        
        ax.axvline(mean_val, color='red', linestyle='--', linewidth=1.5,
                  label=f'Mean = {mean_val:.4f}', zorder=2)
        ax.axvline(median_val, color='green', linestyle='--', linewidth=1.5,
                  label=f'Median = {median_val:.4f}', zorder=2)
        
        # Statistics box
        stats_text = f'''Method: {method}
n = {len(all_scores)}
Mean = {mean_val:.4f}
Median = {median_val:.4f}
Std = {std_val:.4f}
Min = {all_scores.min():.4f}
Max = {all_scores.max():.4f}'''
        
        ax.text(0.98, 0.97, stats_text, transform=ax.transAxes,
               fontsize=9, verticalalignment='top', horizontalalignment='right',
               bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.8),
               family='monospace')
        
        # Styling
        ax.set_xlabel('Composite Score (Criterion-Weighted)', fontsize=11, fontweight='bold')
        ax.set_ylabel('Density', fontsize=11, fontweight='bold')
        ax.set_title(
            title or f'{method} Method: Score Distribution (2011-2024)',
            fontsize=13, fontweight='bold', pad=15
        )
        ax.legend(loc='upper left', fontsize=9, framealpha=0.9)
        ax.grid(True, alpha=0.3, linestyle='--')
        
        save_name = save_name or f'fig09_distribution_{method}.png'
        return self._save(fig, save_name)

    def plot_all_method_distributions(
        self,
        multi_year_results: Dict[int, Any],
    ) -> Optional[List[str]]:
        """
        Create distribution charts for all 6 MCDM methods.
        
        Returns list of saved figure paths.
        """
        paths = []
        for method in _METHODS:
            path = self.plot_method_distribution_all_years(multi_year_results, method)
            if path:
                paths.append(path)
                _logger.info(f'Saved: {path}')
        return paths

    # ==================================================================
    #  FIG10 – Method Agreement Matrix (Spearman ρ, 6×6)
    # ==================================================================

    def plot_method_agreement_matrix(
        self,
        multi_year_results: Dict[int, Any],
        title: str = 'MCDM Method Rank Agreement (Spearman ρ)',
        save_name: str = 'fig10_method_agreement_matrix.png',
    ) -> Optional[str]:
        """
        Spearman rank correlation heatmap showing pairwise agreement between
        all 6 MCDM methods.
        
        Aggregates rankings across all years and provinces to compute
        inter-method correlation.
        
        Design:
          • Clustered heatmap with dendrogram (if scipy available)
          • Diverging colormap (RdBu_r) emphasizing correlation strength
          • Values range [-1, 1] with color scale centered at 0
          • Higher ρ = stronger agreement (redder)
          • Lower ρ = weaker agreement (bluer)
        """
        if not HAS_MATPLOTLIB or not HAS_SCIPY:
            _logger.warning('plot_method_agreement_matrix: scipy unavailable')
            return None

        # Collect all method ranks across all years
        method_ranks_all = {m: [] for m in _METHODS}
        
        for yr in sorted(multi_year_results.keys()):
            result = multi_year_results[yr]
            method_scores = getattr(result, 'criterion_method_scores', {})
            
            if method_scores:
                # Per criterion, rank the methods' scores for each alternative
                # Then aggregate across criteria
                for crit_id in sorted(method_scores.keys()):
                    crit_data = method_scores[crit_id]
                    
                    # Get all method scores for this criterion (as pd.Series for index alignment)
                    methods_data = {}
                    for method in _METHODS:
                        if method in crit_data:
                            series = crit_data[method]
                            # Ensure it's a pandas Series
                            if not isinstance(series, pd.Series):
                                series = pd.Series(series)
                            # Only add if not all NaN
                            if not series.isna().all():
                                methods_data[method] = series
                    
                    if len(methods_data) == len(_METHODS):
                        # All methods have scores - find common index across methods
                        # (provinces that have scores from all methods in this criterion)
                        common_index = None
                        for method, series in methods_data.items():
                            method_index = set(series.index[~series.isna()])
                            if common_index is None:
                                common_index = method_index
                            else:
                                common_index = common_index.intersection(method_index)
                        
                        if common_index and len(common_index) >= 2:
                            # Rank each method's scores
                            for method in _METHODS:
                                try:
                                    scores = methods_data[method].loc[list(common_index)]
                                    ranks = sp_stats.rankdata(scores.values, nan_policy='omit')
                                    method_ranks_all[method].append(ranks)
                                except Exception as e:
                                    _logger.debug(f'Rankdata failed for {method} in {crit_id}: {e}')
                                    continue
        
        # Compute Spearman correlation matrix
        if not method_ranks_all[_METHODS[0]]:
            _logger.debug('plot_method_agreement_matrix: No ranking data found')
            return None

        # Flatten ranks into matrix: n_methods × total_observations
        rank_matrix = []
        for method in _METHODS:
            if method_ranks_all[method]:
                ranks = np.concatenate(method_ranks_all[method])
                rank_matrix.append(ranks)
        
        _logger.debug(f'plot_method_agreement_matrix: Rank matrix shape before corrcoef: {len(rank_matrix)} methods')
        
        rank_matrix = np.array(rank_matrix)
        
        # Compute Spearman correlations
        try:
            corr_matrix = np.corrcoef(rank_matrix)
        except Exception as e:
            _logger.debug(f'plot_method_agreement_matrix: Correlation matrix computation failed: {e}')
            return None
        
        # Check for invalid correlation matrix
        if np.any(np.isnan(corr_matrix)) or np.any(np.isinf(corr_matrix)):
            _logger.debug(f'plot_method_agreement_matrix: Correlation matrix contains NaN/inf - {np.sum(np.isnan(corr_matrix))} NaNs, {np.sum(np.isinf(corr_matrix))} infs')
            return None
        
        # Create figure with clustering
        from scipy.cluster.hierarchy import dendrogram, linkage
        from scipy.spatial.distance import squareform
        
        # Distance matrix from correlations
        dist_matrix = 1 - corr_matrix  # Convert correlation to distance
        
        # Ensure distance matrix is properly formed for squareform
        try:
            # Replace any invalid values in distance matrix
            dist_matrix = np.nan_to_num(dist_matrix, nan=1.0, posinf=1.0, neginf=0.0)
            condensed = squareform(dist_matrix)
            linkage_matrix = linkage(condensed, method='ward')
        except Exception as e:
            _logger.warning(f'Clustering failed: {e}. Using alternative approach.')
            # Fallback: no clustering, just heatmap
            linkage_matrix = None
        
        # Create clustered heatmap
        fig = plt.figure(figsize=(12, 10))
        
        if linkage_matrix is not None:
            # Dendrogram on left, heatmap on right
            ax_dend = fig.add_axes([0.1, 0.1, 0.15, 0.75])
            ax_hm = fig.add_axes([0.3, 0.1, 0.6, 0.75])
            
            dendro = dendrogram(linkage_matrix, ax=ax_dend, orientation='left',
                               labels=_METHODS, no_labels=False)
            ax_dend.set_xlabel('Distance', fontsize=10)
            
            # Reorder methods by dendrogram
            order = np.array(dendro['leaves'])
            ordered_methods = [_METHODS[i] for i in order]
            reordered_corr = corr_matrix[np.ix_(order, order)]
        else:
            # No dendrogram, use original order; create heatmap axes using full figure
            ax_hm = fig.add_axes([0.15, 0.15, 0.7, 0.7])
            ordered_methods = _METHODS
            reordered_corr = corr_matrix
        
        # Heatmap
        cmap = plt.colormaps['RdBu_r']
        im = ax_hm.imshow(reordered_corr, cmap=cmap, aspect='auto', vmin=-1, vmax=1)
        
        # Axes labels
        ax_hm.set_xticks(range(len(ordered_methods)))
        ax_hm.set_yticks(range(len(ordered_methods)))
        ax_hm.set_xticklabels(ordered_methods, rotation=45, ha='right', fontsize=10)
        ax_hm.set_yticklabels(ordered_methods, fontsize=10)
        
        # Add correlation values
        for i in range(len(ordered_methods)):
            for j in range(len(ordered_methods)):
                value = reordered_corr[i, j]
                text_color = 'white' if abs(value) > 0.5 else 'black'
                ax_hm.text(j, i, f'{value:.2f}', ha='center', va='center',
                          color=text_color, fontsize=9, fontweight='bold')
        
        # Colorbar
        cbar = fig.colorbar(im, ax=ax_hm, pad=0.02)
        cbar.set_label('Spearman ρ', fontsize=10, fontweight='bold')
        
        # Title
        fig.suptitle(title, fontsize=13, fontweight='bold', y=0.98)
        
        return self._save(fig, save_name)

    # ==================================================================
    #  FIG11 – Kendall's W Concordance Analysis
    # ==================================================================

    def plot_kendall_w_analysis(
        self,
        multi_year_results: Dict[int, Any],
        save_name: str = 'fig11_kendall_w_analysis.png',
    ) -> Optional[str]:
        """
        Kendall's coefficient of concordance (W) analysis showing inter-method
        agreement over time and across criteria.
        
        Kendall's W ∈ [0, 1]:
          • W = 0: no agreement (methods rank differently)
          • W = 1: perfect agreement (methods rank identically)
          
        Visualizes:
          • Kendall's W per criterion
          • Kendall's W per year
          • Overall W with confidence interval
          • Interpretation zones (poor, moderate, good agreement)
        """
        if not HAS_MATPLOTLIB or not HAS_SCIPY:
            return None

        # Compute Kendall's W per criterion per year
        w_values = {'overall': [], 'by_criterion': {}, 'by_year': {}}
        
        for yr in sorted(multi_year_results.keys()):
            result = multi_year_results[yr]
            method_scores = getattr(result, 'criterion_method_scores', {})
            
            if method_scores:
                year_w_values = []
                
                for crit_id in sorted(method_scores.keys()):
                    crit_data = method_scores[crit_id]
                    
                    # Rank each method's scores (as pd.Series for index alignment)
                    methods_series = {}
                    for method in _METHODS:
                        if method in crit_data:
                            series = crit_data[method]
                            # Ensure it's a pandas Series
                            if not isinstance(series, pd.Series):
                                series = pd.Series(series)
                            # Only add if not all NaN
                            if not series.isna().all():
                                methods_series[method] = series
                    
                    if len(methods_series) == len(_METHODS):
                        # Find common index (alternatives with complete data across all methods)
                        common_index = None
                        for method, series in methods_series.items():
                            method_index = set(series.index[~series.isna()])
                            if common_index is None:
                                common_index = method_index
                            else:
                                common_index = common_index.intersection(method_index)
                        
                        if common_index and len(common_index) >= 2:
                            # Rank each method's scores on common index
                            rank_data = []
                            for method in _METHODS:
                                try:
                                    scores = methods_series[method].loc[list(common_index)]
                                    ranks = sp_stats.rankdata(scores.values, nan_policy='omit')
                                    rank_data.append(ranks)
                                except Exception as e:
                                    _logger.debug(f'Rankdata failed for {method} in {crit_id}: {e}')
                            
                            if len(rank_data) == len(_METHODS):
                                # Compute Kendall's W for this criterion-year
                                rank_matrix = np.array(rank_data)
                                k = rank_matrix.shape[0]  # number of raters (methods)
                                n = rank_matrix.shape[1]  # number of items
                                
                                if k >= 2 and n >= 2:
                                    mean_rank = np.mean(rank_matrix, axis=0)
                                    S = np.sum((mean_rank - (n+1)/2)**2)
                                    W = 12 * S / (k**2 * (n**3 - n))
                                    w_values['overall'].append(W)
                                    year_w_values.append(W)
                                    
                                    if crit_id not in w_values['by_criterion']:
                                        w_values['by_criterion'][crit_id] = []
                                    w_values['by_criterion'][crit_id].append(W)
                
                if year_w_values:
                    w_values['by_year'][yr] = np.mean(year_w_values)
        
        if not w_values['overall']:
            _logger.debug(f'plot_kendall_w_analysis: No Kendall W values computed. by_criterion keys: {list(w_values["by_criterion"].keys())}, by_year keys: {list(w_values["by_year"].keys())}')
            return None

        # Create figure with multiple subplots
        fig, axes = plt.subplots(2, 2, figsize=(14, 10))
        
        # 1. Overall W distribution (histogram)
        ax = axes[0, 0]
        ax.hist(w_values['overall'], bins=20, color=PALETTE['royal_blue'],
               edgecolor='white', linewidth=1, alpha=0.7)
        overall_mean = np.mean(w_values['overall'])
        overall_std = np.std(w_values['overall'])
        ax.axvline(overall_mean, color='red', linestyle='--', linewidth=2,
                  label=f'Mean W = {overall_mean:.3f}')
        ax.set_xlabel("Kendall's W", fontsize=10, fontweight='bold')
        ax.set_ylabel('Frequency', fontsize=10, fontweight='bold')
        ax.set_title("Overall Concordance Distribution", fontsize=11, fontweight='bold')
        ax.legend(fontsize=9)
        ax.grid(True, alpha=0.3)
        
        # 2. W per criterion (bar chart)
        ax = axes[0, 1]
        crit_ids = sorted(w_values['by_criterion'].keys())
        crit_means = [np.mean(w_values['by_criterion'][c]) for c in crit_ids]
        crit_stds = [np.std(w_values['by_criterion'][c]) for c in crit_ids]
        
        x_pos = np.arange(len(crit_ids))
        ax.bar(x_pos, crit_means, yerr=crit_stds, capsize=5,
              color=PALETTE['emerald'], edgecolor='white', linewidth=1, alpha=0.8)
        ax.axhline(overall_mean, color='red', linestyle='--', linewidth=2,
                  label=f'Overall Mean = {overall_mean:.3f}')
        ax.set_xticks(x_pos)
        ax.set_xticklabels(crit_ids, fontsize=9)
        ax.set_ylabel("Kendall's W", fontsize=10, fontweight='bold')
        ax.set_title('Concordance by Criterion', fontsize=11, fontweight='bold')
        ax.legend(fontsize=9)
        ax.grid(True, alpha=0.3, axis='y')
        
        # 3. W per year (line chart)
        ax = axes[1, 0]
        years = sorted(w_values['by_year'].keys())
        w_by_year = [w_values['by_year'][y] for y in years]
        
        ax.plot(years, w_by_year, marker='o', linewidth=2, markersize=6,
               color=PALETTE['royal_blue'], label='Year-wise W')
        ax.fill_between(years, 
                        np.array(w_by_year) - np.std(w_values['overall']),
                        np.array(w_by_year) + np.std(w_values['overall']),
                        alpha=0.2, color=PALETTE['royal_blue'])
        ax.axhline(overall_mean, color='red', linestyle='--', linewidth=2,
                  label=f'Mean = {overall_mean:.3f}')
        ax.set_xlabel('Year', fontsize=10, fontweight='bold')
        ax.set_ylabel("Kendall's W", fontsize=10, fontweight='bold')
        ax.set_title('Temporal Concordance Trend', fontsize=11, fontweight='bold')
        ax.legend(fontsize=9)
        ax.grid(True, alpha=0.3)
        
        # 4. Interpretation zones
        ax = axes[1, 1]
        ax.axis('off')
        
        interpretation = f"""
KENDALL'S W INTERPRETATION

Overall W = {overall_mean:.4f}

Agreement Scale:
  0.0 – 0.33:  Poor/Weak
  0.33 – 0.67: Moderate/Fair
  0.67 – 1.0:  Strong/Excellent

Range (min–max): {min(w_values['overall']):.4f} – {max(w_values['overall']):.4f}
Std Dev: {overall_std:.4f}
Sample Size: {len(w_values['overall'])}

Critical Value (p < 0.05):
  Approximate threshold ≈ 0.05 + 1.96√(var)

Conclusion:
  Methods show {'STRONG' if overall_mean > 0.67 else 'MODERATE' if overall_mean > 0.33 else 'WEAK'}
  agreement in ranking alternatives across
  criteria and time periods.
        """
        
        ax.text(0.1, 0.9, interpretation, transform=ax.transAxes,
               fontsize=10, verticalalignment='top', family='monospace',
               bbox=dict(boxstyle='round', facecolor='lightblue', alpha=0.3))
        
        fig.suptitle("Kendall's W: Multi-Method Concordance Analysis",
                    fontsize=13, fontweight='bold', y=0.995)
        plt.tight_layout(rect=[0, 0, 1, 0.99])
        
        return self._save(fig, save_name)

    # ==================================================================
    #  FIG12 – Rank Profiles
    # ==================================================================

    def plot_rank_profiles(
        self,
        multi_year_results: Dict[int, Any],
        top_n: int = 15,
        save_name: str = 'fig12_rank_profiles.png',
    ) -> Optional[str]:
        """
        Multi-method rank profiles for top-N alternatives.
        
        Shows how each method ranks the same alternatives, revealing consensus
        and disagreement patterns.
        
        Visualizes:
          • Parallel lines for top-N alternatives
          • One vertical axis per method
          • Line color/thickness indicates ranking consistency
        """
        if not HAS_MATPLOTLIB:
            return None

        # Get latest year results for clarity
        latest_year = max(multi_year_results.keys())
        result = multi_year_results[latest_year]
        final_ranking = getattr(result, 'final_ranking', None)
        final_scores = getattr(result, 'final_scores', None)

        if final_ranking is None or final_scores is None:
            return None

        # Get top-N alternatives
        top_indices = np.argsort(final_ranking.values)[:top_n]
        top_provinces = final_ranking.index[top_indices]
        
        # Get method-specific ranks for each method
        method_scores = getattr(result, 'criterion_method_scores', {})
        if not method_scores:
            return None

        # Create score DataFrame by aggregating across criteria
        method_composite_scores = {m: {} for m in _METHODS}
        
        for crit_id in sorted(method_scores.keys()):
            crit_data = method_scores[crit_id]
            for method in _METHODS:
                if method in crit_data:
                    for prov, score in crit_data[method].items():
                        if prov not in method_composite_scores[method]:
                            method_composite_scores[method][prov] = []
                        method_composite_scores[method][prov].append(score)
        
        # Convert to DataFrames and rank
        method_ranks = {}
        for method in _METHODS:
            scores = method_composite_scores[method]
            if scores:
                scores_series = pd.Series({
                    prov: np.nanmean(scores[prov]) 
                    for prov in scores if prov in top_provinces
                })
                method_ranks[method] = sp_stats.rankdata(-scores_series.values)

        if not method_ranks:
            return None

        # Create parallel coordinates plot
        fig, ax = plt.subplots(figsize=(14, 8))
        
        x_positions = np.arange(len(_METHODS))
        colors = plt.cm.Set3(np.linspace(0, 1, len(top_provinces)))
        
        lines_created = 0
        for i, prov in enumerate(top_provinces):
            ranks_for_prov = []
            for method in _METHODS:
                if method in method_ranks:
                    idx = np.where(np.array(top_provinces) == prov)[0][0]
                    if idx < len(method_ranks[method]):
                        ranks_for_prov.append(method_ranks[method][idx])
            
            if len(ranks_for_prov) == len(_METHODS):
                # Determine line style based on variance
                rank_variance = np.std(ranks_for_prov)
                linewidth = 0.8 + rank_variance / 10
                alpha = 0.9 - rank_variance / 20
                
                # Only add label to first 15 lines to avoid legend overflow
                label_text = f'{prov}' if lines_created < 15 else None
                ax.plot(x_positions, ranks_for_prov, marker='o', 
                       color=colors[i], linewidth=linewidth, alpha=alpha,
                       markersize=5, label=label_text)
                lines_created += 1
        
        ax.set_xticks(x_positions)
        ax.set_xticklabels(_METHODS, fontsize=10, fontweight='bold')
        ax.set_ylabel('Rank (1 = Best)', fontsize=11, fontweight='bold')
        ax.set_title(f'Rank Profiles: Top-{top_n} Alternatives (Year {latest_year})',
                    fontsize=13, fontweight='bold', pad=15)
        ax.invert_yaxis()
        ax.grid(True, alpha=0.3, axis='y')
        
        # Only add legend if lines were created with labels
        if lines_created > 0:
            ax.legend(bbox_to_anchor=(1.05, 1), loc='upper left', fontsize=8, ncol=1)
        
        plt.tight_layout()
        return self._save(fig, save_name)

    # ==================================================================
    #  FIG13 – Method Boxplots (Distribution Comparison)
    # ==================================================================

    def plot_method_boxplots(
        self,
        multi_year_results: Dict[int, Any],
        save_name: str = 'fig13_method_boxplots.png',
    ) -> Optional[str]:
        """
        Boxplots comparing score distributions across all 6 MCDM methods.
        
        Shows:
          • Median (line in box)
          • Q1-Q3 range (box)
          • Whiskers (1.5*IQR)
          • Outliers (points)
          
        Design for discrimination: individual method scales enabled for
        better comparison of discriminatory power.
        """
        if not HAS_MATPLOTLIB:
            return None

        # Collect scores per method
        method_scores_list = {m: [] for m in _METHODS}
        
        for yr in sorted(multi_year_results.keys()):
            result = multi_year_results[yr]
            crit_scores = getattr(result, 'criterion_method_scores', {})
            
            for crit_id in sorted(crit_scores.keys()):
                crit_data = crit_scores[crit_id]
                for method in _METHODS:
                    if method in crit_data:
                        scores = crit_data[method]
                        if hasattr(scores, 'values'):
                            scores = scores.values
                        method_scores_list[method].extend(scores[~np.isnan(scores)])
        
        # Create boxplots
        fig, ax = plt.subplots(figsize=(12, 7))
        
        data_to_plot = [method_scores_list[m] for m in _METHODS]
        bp = ax.boxplot(data_to_plot, labels=_METHODS, patch_artist=True,
                       widths=0.6, showmeans=True, meanline=False)
        
        # Color boxes by method
        for patch, method in zip(bp['boxes'], _METHODS):
            patch.set_facecolor(_METHOD_COLORS[method])
            patch.set_alpha(0.7)
            patch.set_edgecolor('white')
            patch.set_linewidth(1.5)
        
        # Style other elements
        for element in ['whiskers', 'fliers', 'means', 'medians', 'caps']:
            plt.setp(bp[element], color='black', linewidth=1.5)
        
        # Add sample size annotations
        for i, method in enumerate(_METHODS):
            n = len(method_scores_list[method])
            mean_val = np.mean(method_scores_list[method])
            ax.text(i+1, max(method_scores_list[method]), f'n={n}',
                   ha='center', fontsize=9, style='italic')
        
        ax.set_ylabel('Composite Score', fontsize=11, fontweight='bold')
        ax.set_title('MCDM Method Score Distributions (2011-2024)',
                    fontsize=13, fontweight='bold', pad=15)
        ax.grid(True, alpha=0.3, axis='y')
        
        return self._save(fig, save_name)

    # ==================================================================
    #  FIG14 – Method Scatter Plots (Pairwise Comparison)
    # ==================================================================

    def plot_method_scatter_comparison(
        self,
        multi_year_results: Dict[int, Any],
        save_name: str = 'fig14_method_scatter.png',
    ) -> Optional[str]:
        """
        Pairwise scatter plots comparing methods (6×6 grid of scatter plots).
        
        Shows:
          • Relationship between method scores
          • Strength of agreement (diagonal = perfect agreement)
          • Regression line for trend
          • Spearman correlation coefficient
        """
        if not HAS_MATPLOTLIB or not HAS_SCIPY:
            return None

        # Aggregate composite scores per method across all years/provinces
        method_scores_df = {m: {} for m in _METHODS}
        
        for yr in sorted(multi_year_results.keys()):
            result = multi_year_results[yr]
            crit_scores = getattr(result, 'criterion_method_scores', {})
            
            # Get provinces
            if crit_scores:
                first_crit = next(iter(crit_scores.values()), {})
                first_method = next(iter(first_crit.values()), None)
                if first_method is not None:
                    provinces = first_method.index if hasattr(first_method, 'index') else []
                    
                    for method in _METHODS:
                        for prov in provinces:
                            if prov not in method_scores_df[method]:
                                method_scores_df[method][prov] = []
                            
                            # Average across criteria
                            crit_vals = []
                            for crit_id in sorted(crit_scores.keys()):
                                crit_data = crit_scores[crit_id]
                                if method in crit_data:
                                    series = crit_data[method]
                                    if hasattr(series, 'loc') and prov in series.index:
                                        crit_vals.append(series.loc[prov])
                            
                            if crit_vals:
                                method_scores_df[method][prov].append(np.nanmean(crit_vals))
        
        # Convert to composite scores (skip empty val lists)
        method_composite = {}
        for method in _METHODS:
            if method_scores_df[method]:
                method_composite[method] = {
                    prov: np.nanmean(vals) 
                    for prov, vals in method_scores_df[method].items() if vals
                }
        
        # Create 6×6 grid of scatter plots
        fig, axes = plt.subplots(len(_METHODS), len(_METHODS), figsize=(16, 14))
        
        for i, m1 in enumerate(_METHODS):
            for j, m2 in enumerate(_METHODS):
                ax = axes[i, j]
                
                if i == j:
                    # Diagonal: distribution (histogram)
                    if m1 in method_composite:
                        scores = list(method_composite[m1].values())
                        ax.hist(scores, bins=15, color=_METHOD_COLORS[m1], 
                               alpha=0.7, edgecolor='white')
                        ax.set_ylabel(m1, fontsize=9, fontweight='bold')
                else:
                    # Off-diagonal: scatter plot
                    if m1 in method_composite and m2 in method_composite:
                        # Align by common provinces
                        common_provs = set(method_composite[m1].keys()) & set(method_composite[m2].keys())
                        
                        if common_provs:
                            x = np.array([method_composite[m2][p] for p in common_provs])
                            y = np.array([method_composite[m1][p] for p in common_provs])
                            
                            # Scatter
                            ax.scatter(x, y, alpha=0.5, s=30, color=_METHOD_COLORS[m1],
                                     edgecolor='white', linewidth=0.5)
                            
                            # Regression line
                            if len(x) > 2:
                                z = np.polyfit(x, y, 1)
                                p = np.poly1d(z)
                                x_line = np.linspace(x.min(), x.max(), 100)
                                ax.plot(x_line, p(x_line), 'r--', linewidth=1.5, alpha=0.7)
                                
                                # Spearman correlation
                                rho, _ = sp_stats.spearmanr(x, y)
                                ax.text(0.05, 0.95, f'ρ={rho:.2f}', 
                                       transform=ax.transAxes, fontsize=9,
                                       bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.7),
                                       verticalalignment='top')
                            
                            if i == len(_METHODS) - 1:
                                ax.set_xlabel(m2, fontsize=9, fontweight='bold')
                            if j == 0:
                                ax.set_ylabel(m1, fontsize=9, fontweight='bold')
                
                ax.grid(True, alpha=0.2)
                ax.tick_params(labelsize=7)
        
        fig.suptitle('MCDM Method Pairwise Score Comparisons', 
                    fontsize=13, fontweight='bold', y=0.995)
        plt.tight_layout(rect=[0, 0, 1, 0.99])
        
        return self._save(fig, save_name)

    # ==================================================================
    #  FIG15 – Perturbation Sensitivity Analysis
    # ==================================================================

    def plot_perturbation_sensitivity(
        self,
        multi_year_results: Dict[int, Any],
        perturbation_results: Optional[Dict[str, Any]] = None,
        save_name: str = 'fig15_perturbation_sensitivity.png',
    ) -> Optional[str]:
        """
        Perturbation sensitivity analysis: impact of criterion weight changes
        on method stability.
        
        Shows:
          • Tolerance bands: how much weight can change without changing rank
          • Method robustness: which methods are most stable
          • Critical criteria: which criteria most affect results
        """
        if not HAS_MATPLOTLIB:
            return None

        # If perturbation results not provided, compute basic robustness measures
        # by analyzing score variance within criteria
        
        latest_year = max(multi_year_results.keys())
        result = multi_year_results[latest_year]
        crit_scores = getattr(result, 'criterion_method_scores', {})
        
        if not crit_scores:
            return None

        # Compute within-criterion robustness for each method
        method_robustness = {m: [] for m in _METHODS}
        
        for crit_id in sorted(crit_scores.keys()):
            crit_data = crit_scores[crit_id]
            for method in _METHODS:
                if method in crit_data:
                    scores = crit_data[method]
                    if hasattr(scores, 'values'):
                        scores = scores.values
                    # Robustness = 1 - coefficient of variation
                    cv = np.std(scores) / (np.mean(scores) + 1e-10)
                    robustness = 1 - cv
                    method_robustness[method].append(max(0, robustness))
        
        # Create figure
        fig, axes = plt.subplots(2, 2, figsize=(14, 10))
        
        # 1. Method robustness (bar chart)
        ax = axes[0, 0]
        robustness_means = [np.mean(method_robustness[m]) for m in _METHODS]
        robustness_stds = [np.std(method_robustness[m]) for m in _METHODS]
        
        x_pos = np.arange(len(_METHODS))
        bars = ax.bar(x_pos, robustness_means, yerr=robustness_stds, capsize=5,
                     color=[_METHOD_COLORS[m] for m in _METHODS], 
                     edgecolor='white', linewidth=1, alpha=0.8)
        
        ax.set_xticks(x_pos)
        ax.set_xticklabels(_METHODS, fontsize=10, fontweight='bold')
        ax.set_ylabel('Robustness Score', fontsize=10, fontweight='bold')
        ax.set_title('Method Stability (Criterion Stability)', fontsize=11, fontweight='bold')
        ax.set_ylim([0, 1])
        ax.grid(True, alpha=0.3, axis='y')
        
        # Add value labels
        for bar, val in zip(bars, robustness_means):
            height = bar.get_height()
            ax.text(bar.get_x() + bar.get_width()/2., height,
                   f'{val:.2f}', ha='center', va='bottom', fontsize=9)
        
        # 2. Robustness per criterion
        ax = axes[0, 1]
        crit_robustness = {}
        for crit_id in sorted(crit_scores.keys()):
            crit_data = crit_scores[crit_id]
            crit_robs = []
            for method in _METHODS:
                if method in crit_data:
                    scores = crit_data[method]
                    if hasattr(scores, 'values'):
                        scores = scores.values
                    cv = np.std(scores) / (np.mean(scores) + 1e-10)
                    robustness = 1 - cv
                    crit_robs.append(max(0, robustness))
            if crit_robs:
                crit_robustness[crit_id] = np.mean(crit_robs)
        
        crit_ids = sorted(crit_robustness.keys())
        crit_vals = [crit_robustness[c] for c in crit_ids]
        
        x_pos_crit = np.arange(len(crit_ids))
        ax.bar(x_pos_crit, crit_vals, color=PALETTE['teal'], 
              edgecolor='white', linewidth=1, alpha=0.8)
        ax.set_xticks(x_pos_crit)
        ax.set_xticklabels(crit_ids, fontsize=9)
        ax.set_ylabel('Robustness', fontsize=10, fontweight='bold')
        ax.set_title('Criterion Stability', fontsize=11, fontweight='bold')
        ax.set_ylim([0, 1])
        ax.grid(True, alpha=0.3, axis='y')
        
        # 3. Variance within criteria (heatmap)
        ax = axes[1, 0]
        variance_matrix = []
        for method in _METHODS:
            method_vars = []
            for crit_id in sorted(crit_scores.keys()):
                crit_data = crit_scores[crit_id]
                if method in crit_data:
                    scores = crit_data[method]
                    if hasattr(scores, 'values'):
                        scores = scores.values
                    var = np.var(scores)
                    method_vars.append(var)
                else:
                    method_vars.append(np.nan)
            variance_matrix.append(method_vars)
        
        variance_matrix = np.array(variance_matrix)
        im = ax.imshow(variance_matrix, cmap='YlOrRd', aspect='auto')
        
        ax.set_xticks(np.arange(len(crit_ids)))
        ax.set_yticks(np.arange(len(_METHODS)))
        ax.set_xticklabels(crit_ids, fontsize=9)
        ax.set_yticklabels(_METHODS, fontsize=9)
        ax.set_xlabel('Criterion', fontsize=10, fontweight='bold')
        ax.set_ylabel('Method', fontsize=10, fontweight='bold')
        ax.set_title('Score Variance by Method & Criterion', fontsize=11, fontweight='bold')
        
        # Add values
        for i in range(len(_METHODS)):
            for j in range(len(crit_ids)):
                if not np.isnan(variance_matrix[i, j]):
                    ax.text(j, i, f'{variance_matrix[i, j]:.2f}',
                           ha='center', va='center', color='black', fontsize=8)
        
        cbar = plt.colorbar(im, ax=ax)
        cbar.set_label('Variance', fontsize=9, fontweight='bold')
        
        # 4. Robustness summary text
        ax = axes[1, 1]
        ax.axis('off')
        
        summary_text = f"""
PERTURBATION SENSITIVITY SUMMARY

Most Robust Method:
  {max(zip(robustness_means, _METHODS))[1]} (robustness = {max(robustness_means):.3f})

Least Robust Method:
  {min(zip(robustness_means, _METHODS))[1]} (robustness = {min(robustness_means):.3f})

Most Sensitive Criterion:
  {min(zip(crit_vals, crit_ids))[1]} (robustness = {min(crit_vals):.3f})

Most Stable Criterion:
  {max(zip(crit_vals, crit_ids))[1]} (robustness = {max(crit_vals):.3f})

Interpretation:
  • Higher robustness = more insensitive to
    weight changes
  • Lower robustness = sensitive to criterion
    weight perturbations
  • Stable criteria: results less affected by
    small weight changes
        """
        
        ax.text(0.05, 0.95, summary_text, transform=ax.transAxes,
               fontsize=9, verticalalignment='top', family='monospace',
               bbox=dict(boxstyle='round', facecolor='lightyellow', alpha=0.5))
        
        fig.suptitle('Perturbation Sensitivity & Robustness Analysis (Latest Year)',
                    fontsize=13, fontweight='bold', y=0.995)
        plt.tight_layout(rect=[0, 0, 1, 0.99])
        
        return self._save(fig, save_name)


__all__ = ['MCDMRankingPlotter']
